/**
 * Value Creation Challenge - Decision Cards Configuration
 * 75 total decision cards: 25 Grow + 25 Optimize + 25 Sustain
 * 15 cards available per round (5 per category)
 * 
 * NOTE: Impact values are placeholder estimates and will be tuned during Phase 7
 */

import type { Decision, RoundNumber } from '../types/game.js';

// =============================================================================
// GROW DECISIONS (25 total - 5 per round)
// =============================================================================

const GROW_DECISIONS: Decision[] = [
  // ===== ROUND 1 =====
  {
    id: 'grow-1-1',
    category: 'grow',
    subcategory: 'Scale R&D for Next-Gen Portfolio',
    name: 'Advanced Powertrain R&D Expansion',
    narrative: 'Invest in expanding R&D capabilities for next-generation vehicle powertrains and propulsion systems. This positions Magna to capture growing market share in advanced mobility but requires significant upfront investment with returns materializing over 2-3 years.',
    cost: 250,
    impactMagnitude: 4,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Position for recovery',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.03,
    recurringBenefit: 150,
  },
  {
    id: 'grow-1-2',
    category: 'grow',
    subcategory: 'Enter New Geography / Market',
    name: 'Southeast Asia Market Entry',
    narrative: 'Establish manufacturing presence in Thailand/Vietnam to serve growing ASEAN automotive market. Lower labor costs and proximity to emerging markets, but execution risk in new geography.',
    cost: 300,
    impactMagnitude: 3,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: true,
    durationYears: 2,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.025,
    recurringBenefit: 120,
  },
  {
    id: 'grow-1-3',
    category: 'grow',
    subcategory: 'Expand Manufacturing Footprint',
    name: 'Mexico Capacity Expansion',
    narrative: 'Expand existing Mexican operations to increase capacity for North American OEMs. Nearshoring trend favors this investment with relatively predictable returns.',
    cost: 200,
    impactMagnitude: 3,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Position for recovery',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.02,
    recurringBenefit: 80,
  },
  {
    id: 'grow-1-4',
    category: 'grow',
    subcategory: 'JV / Strategic Partnership',
    name: 'Battery Technology JV',
    narrative: 'Form joint venture with battery cell manufacturer to secure supply and develop integrated battery systems. Strategic hedge against vertical integration by OEMs.',
    cost: 350,
    impactMagnitude: 4,
    introducedYear: 1,
    type: 'inorganic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.035,
    recurringBenefit: 140,
  },
  {
    id: 'grow-1-5',
    category: 'grow',
    subcategory: 'Launch a New Business',
    name: 'Autonomous Driving Systems Unit',
    narrative: 'Launch dedicated business unit for advanced driver assistance systems (ADAS) and autonomous driving technology. High potential but uncertain returns as technology evolves rapidly.',
    cost: 400,
    impactMagnitude: 5,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Position for recovery',
    isRisky: true,
    durationYears: 2,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.04,
    recurringBenefit: 180,
  },

  // ===== ROUND 2 =====
  {
    id: 'grow-2-1',
    category: 'grow',
    subcategory: 'Acquire a Business',
    name: 'Bolt-on Sensor Acquisition',
    narrative: 'Acquire small sensor technology company to enhance ADAS capabilities. Adds specialized engineering talent and IP. Integration risk exists but accelerates time-to-market.',
    cost: 280,
    impactMagnitude: 3,
    introducedYear: 2,
    type: 'inorganic',
    guidingPrinciple: 'Balance sheet flexibility enables opportunism',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.015,
    recurringBenefit: 70,
  },
  {
    id: 'grow-2-2',
    category: 'grow',
    subcategory: 'Platform-Level Technology Bets',
    name: 'Software-Defined Vehicle Platform',
    narrative: 'Develop modular software platform for next-gen vehicle architectures. Major bet on industry direction with potential for significant recurring revenue if adopted widely.',
    cost: 450,
    impactMagnitude: 5,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: 'Position for recovery',
    isRisky: true,
    durationYears: 2,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.05,
    recurringBenefit: 200,
  },
  {
    id: 'grow-2-3',
    category: 'grow',
    subcategory: 'Expand Manufacturing Footprint',
    name: 'European Advanced Assembly Facility',
    narrative: 'Build dedicated advanced vehicle assembly plant in Eastern Europe. Positions for European regulatory requirements and next-gen vehicle platforms. Significant investment with long payback period.',
    cost: 500,
    impactMagnitude: 4,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: 'Position for recovery',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.04,
    recurringBenefit: 160,
  },
  {
    id: 'grow-2-4',
    category: 'grow',
    subcategory: 'Expand Manufacturing Footprint',
    name: 'Diversified OEM Capacity Investment',
    narrative: 'Invest in flexible manufacturing capacity additions across existing facilities to serve multiple OEM customers. Spreads investment across GM, Ford, Stellantis, and Toyota programs. Lower per-unit returns but diversified risk exposure. Requires more coordination but provides insurance against customer-specific disruptions.',
    cost: 200,
    impactMagnitude: 3,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.018,
    recurringBenefit: 80,
    riskPrevention: 'oem_program_cancellation',
  },
  {
    id: 'grow-2-5',
    category: 'grow',
    subcategory: 'Expand Manufacturing Footprint',
    name: 'Concentrated OEM Capacity Investment',
    narrative: 'Major capacity investment dedicated to a single OEM\'s flagship vehicle program. The OEM has committed to unprecedented volumes and offered favorable terms for exclusive supply. Higher projected returns than diversified approach, with dedicated production lines and simpler logistics. A strategic bet on this OEM\'s success.',
    cost: 180,
    impactMagnitude: 4,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: 'Position for recovery',
    isRisky: false,  // Not flagged as risky - that's the trap!
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    revenueImpact: 0.028,
    recurringBenefit: 120,
    // NOTE: This decision's returns go to $0 when OEM Program Cancellation event triggers in Round 3
    vulnerableTo: 'oem_program_cancellation',
  },

  // ===== ROUND 3 =====
  {
    id: 'grow-3-1',
    category: 'grow',
    subcategory: 'Acquire a Business',
    name: 'Distressed Competitor Acquisition',
    narrative: 'Opportunity to acquire struggling competitor at attractive valuation. Significant capacity and customer relationships, but integration complexity and some legacy issues.',
    cost: 600,
    impactMagnitude: 5,
    introducedYear: 3,
    type: 'inorganic',
    guidingPrinciple: 'Balance sheet flexibility enables opportunism',
    isRisky: true,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.08,
    recurringBenefit: 250,
  },
  {
    id: 'grow-3-2',
    category: 'grow',
    subcategory: 'JV / Strategic Partnership',
    name: 'Chinese OEM Partnership',
    narrative: 'Strategic partnership with leading Chinese automotive manufacturer. Access to largest automotive growth market but geopolitical and IP concerns. High reward potential with elevated risk.',
    cost: 350,
    impactMagnitude: 4,
    introducedYear: 3,
    type: 'inorganic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: true,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.05,
    recurringBenefit: 180,
  },
  {
    id: 'grow-3-3',
    category: 'grow',
    subcategory: 'Expand Manufacturing Footprint',
    name: 'North America Advanced Component Hub',
    narrative: 'Consolidate and expand advanced component manufacturing in dedicated facility. Economies of scale but requires significant commitment during uncertain market conditions.',
    cost: 380,
    impactMagnitude: 4,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: 'Cash optionality matters',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.035,
    recurringBenefit: 140,
  },
  {
    id: 'grow-3-4',
    category: 'grow',
    subcategory: 'Launch a New Business',
    name: 'Vehicle-to-Grid Services Business',
    narrative: 'Enter emerging V2G (vehicle-to-grid) services market. Early mover opportunity but market development highly uncertain. Could be transformational or premature.',
    cost: 200,
    impactMagnitude: 3,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: 'Position for recovery',
    isRisky: true,
    durationYears: 1,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.015,
    recurringBenefit: 60,
  },
  {
    id: 'grow-3-5',
    category: 'grow',
    subcategory: 'Scale R&D for Next-Gen Portfolio',
    name: 'Solid-State Battery Research',
    narrative: 'Invest in next-generation solid-state battery technology research. Could leapfrog current technology but commercialization timeline uncertain.',
    cost: 280,
    impactMagnitude: 4,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: 'Position for recovery',
    isRisky: true,
    durationYears: 2,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.025,
    recurringBenefit: 120,
  },

  // ===== ROUND 4 =====
  {
    id: 'grow-4-1',
    category: 'grow',
    subcategory: 'Acquire a Business',
    name: 'Opportunistic Acquisition - Premium Supplier',
    narrative: 'Rare opportunity to acquire premium supplier at recession-driven valuation. Strong customer relationships and margins. Requires significant capital during challenging times.',
    cost: 700,
    impactMagnitude: 5,
    introducedYear: 4,
    type: 'inorganic',
    guidingPrinciple: 'Balance sheet flexibility enables opportunism',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.07,
    recurringBenefit: 280,
  },
  {
    id: 'grow-4-2',
    category: 'grow',
    subcategory: 'Platform-Level Technology Bets',
    name: 'Modular Vehicle Platform',
    narrative: 'Develop flexible modular platform that can underpin multiple vehicle types and powertrains. Major investment during downturn positions for recovery leadership.',
    cost: 550,
    impactMagnitude: 5,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: 'Position for recovery',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.06,
    recurringBenefit: 220,
  },
  {
    id: 'grow-4-3',
    category: 'grow',
    subcategory: 'Enter New Geography / Market',
    name: 'Middle East Manufacturing Partnership',
    narrative: 'Partnership with Gulf state sovereign wealth fund for new manufacturing hub. Diversifies geographic exposure and provides capital, but execution complexity.',
    cost: 300,
    impactMagnitude: 3,
    introducedYear: 4,
    type: 'inorganic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.02,
    recurringBenefit: 90,
  },
  {
    id: 'grow-4-4',
    category: 'grow',
    subcategory: 'JV / Strategic Partnership',
    name: 'Hydrogen Fuel Cell Alliance',
    narrative: 'Join consortium developing hydrogen fuel cell technology for commercial vehicles. Hedges powertrain technology bets but requires ongoing investment with uncertain payoff timeline.',
    cost: 180,
    impactMagnitude: 2,
    introducedYear: 4,
    type: 'inorganic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: true,
    durationYears: 2,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.01,
    recurringBenefit: 50,
  },
  {
    id: 'grow-4-5',
    category: 'grow',
    subcategory: 'Expand Manufacturing Footprint',
    name: 'Underutilized Capacity Purchase',
    narrative: 'Purchase underutilized manufacturing facility from distressed competitor at significant discount. Ready infrastructure but requires investment to modernize.',
    cost: 250,
    impactMagnitude: 3,
    introducedYear: 4,
    type: 'inorganic',
    guidingPrinciple: 'Balance sheet flexibility enables opportunism',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.025,
    recurringBenefit: 100,
  },

  // ===== ROUND 5 =====
  {
    id: 'grow-5-1',
    category: 'grow',
    subcategory: 'Acquire a Business',
    name: 'Strategic Technology Acquisition',
    narrative: 'Acquire emerging technology company with breakthrough thermal management system for advanced vehicles. Positions for next-generation vehicle requirements. Premium valuation as market recovers.',
    cost: 400,
    impactMagnitude: 4,
    introducedYear: 5,
    type: 'inorganic',
    guidingPrinciple: 'Position for recovery',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.03,
    recurringBenefit: 130,
  },
  {
    id: 'grow-5-2',
    category: 'grow',
    subcategory: 'Scale R&D for Next-Gen Portfolio',
    name: 'Next-Gen ADAS Development',
    narrative: 'Accelerate development of Level 4 autonomous driving capabilities. Recovery enables increased R&D spending. Positions for 2030s autonomous vehicle requirements.',
    cost: 350,
    impactMagnitude: 4,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: 'Position for recovery',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.04,
    recurringBenefit: 160,
  },
  {
    id: 'grow-5-3',
    category: 'grow',
    subcategory: 'Expand Manufacturing Footprint',
    name: 'Global Capacity Expansion Program',
    narrative: 'Comprehensive capacity expansion across multiple regions to meet recovering demand. Significant investment but positions for sustainable growth trajectory.',
    cost: 600,
    impactMagnitude: 5,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: 'Position for recovery',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.06,
    recurringBenefit: 240,
  },
  {
    id: 'grow-5-4',
    category: 'grow',
    subcategory: 'Launch a New Business',
    name: 'Mobility Services Platform',
    narrative: 'Launch platform to support fleet operators and mobility-as-a-service providers. Diversifies revenue model and creates recurring revenue streams.',
    cost: 250,
    impactMagnitude: 3,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.02,
    recurringBenefit: 80,
  },
  {
    id: 'grow-5-5',
    category: 'grow',
    subcategory: 'JV / Strategic Partnership',
    name: 'OEM Strategic Alliance',
    narrative: 'Deep strategic partnership with major OEM for exclusive supply arrangements. Secures significant volume but concentration risk. Attractive terms as OEM seeks reliable supplier.',
    cost: 200,
    impactMagnitude: 4,
    introducedYear: 5,
    type: 'inorganic',
    guidingPrinciple: 'Position for recovery',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    revenueImpact: 0.05,
    recurringBenefit: 200,
  },
];

// =============================================================================
// OPTIMIZE DECISIONS (25 total - 5 per round)
// =============================================================================

const OPTIMIZE_DECISIONS: Decision[] = [
  // ===== ROUND 1 =====
  {
    id: 'optimize-1-1',
    category: 'optimize',
    subcategory: 'Factory of the Future',
    name: 'Smart Factory Pilot Program',
    narrative: 'Implement Industry 4.0 technologies in flagship facility. IoT sensors, AI-driven quality control, and predictive maintenance. Proof of concept for broader rollout.',
    cost: 150,
    impactMagnitude: 3,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    cogsImpact: -0.01,
    recurringBenefit: 60,
  },
  {
    id: 'optimize-1-2',
    category: 'optimize',
    subcategory: 'SG&A Optimization',
    name: 'Shared Services Consolidation',
    narrative: 'Consolidate back-office functions (finance, HR, IT) into regional shared services centers. Upfront investment yields ongoing cost savings.',
    cost: 80,
    impactMagnitude: 2,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    sgaImpact: -0.02,
    recurringBenefit: 40,
  },
  {
    id: 'optimize-1-3',
    category: 'optimize',
    subcategory: 'Global Supply Chain Redesign',
    name: 'Supplier Dual-Sourcing Initiative',
    narrative: 'Establish secondary suppliers for critical components. Increases supply chain resilience and negotiating leverage. Small cost premium offset by risk reduction.',
    cost: 100,
    impactMagnitude: 3,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    cogsImpact: 0.005,
    riskPrevention: 'supply_chain_disruption',
    recurringBenefit: 30,
  },
  {
    id: 'optimize-1-4',
    category: 'optimize',
    subcategory: 'Enterprise Digital Transformation',
    name: 'ERP System Upgrade',
    narrative: 'Upgrade enterprise resource planning system to modern cloud-based platform. Enables better data analytics and process automation.',
    cost: 120,
    impactMagnitude: 2,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    sgaImpact: -0.01,
    cogsImpact: -0.005,
    recurringBenefit: 50,
  },
  {
    id: 'optimize-1-5',
    category: 'optimize',
    subcategory: 'Organizational Restructure',
    name: 'Management Delayering',
    narrative: 'Remove one layer of middle management to improve decision speed and reduce overhead. Short-term disruption but lasting efficiency gains.',
    cost: 60,
    impactMagnitude: 2,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    sgaImpact: -0.015,
    recurringBenefit: 35,
  },

  // ===== ROUND 2 =====
  {
    id: 'optimize-2-1',
    category: 'optimize',
    subcategory: 'Factory of the Future',
    name: 'Automation Expansion Program',
    narrative: 'Expand robotic automation across manufacturing facilities. Higher upfront cost but significant labor cost reduction and quality improvement.',
    cost: 250,
    impactMagnitude: 4,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    cogsImpact: -0.02,
    recurringBenefit: 100,
  },
  {
    id: 'optimize-2-2',
    category: 'optimize',
    subcategory: 'Select Group Transformation',
    name: 'Underperforming Division Turnaround',
    narrative: 'Comprehensive operational improvement program for underperforming business unit. New leadership, process redesign, and targeted investments.',
    cost: 180,
    impactMagnitude: 3,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    cogsImpact: -0.015,
    sgaImpact: -0.01,
    recurringBenefit: 80,
  },
  {
    id: 'optimize-2-3',
    category: 'optimize',
    subcategory: 'Global Supply Chain Redesign',
    name: 'Logistics Network Optimization',
    narrative: 'Redesign global logistics network to reduce transportation costs and improve delivery times. Consolidate warehouses and optimize routes.',
    cost: 140,
    impactMagnitude: 3,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    cogsImpact: -0.01,
    recurringBenefit: 55,
  },
  {
    id: 'optimize-2-4',
    category: 'optimize',
    subcategory: 'SG&A Optimization',
    name: 'Procurement Excellence Program',
    narrative: 'Implement strategic sourcing and supplier management program. Leverage scale for better pricing and terms on indirect spend.',
    cost: 70,
    impactMagnitude: 2,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    sgaImpact: -0.01,
    cogsImpact: -0.005,
    recurringBenefit: 45,
  },
  {
    id: 'optimize-2-5',
    category: 'optimize',
    subcategory: 'Enterprise Digital Transformation',
    name: 'Advanced Analytics Platform',
    narrative: 'Deploy enterprise analytics platform to improve decision-making across operations. Predictive insights for demand planning, quality, and maintenance.',
    cost: 100,
    impactMagnitude: 2,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    cogsImpact: -0.008,
    sgaImpact: -0.005,
    recurringBenefit: 50,
  },

  // ===== ROUND 3 =====
  {
    id: 'optimize-3-1',
    category: 'optimize',
    subcategory: 'Divest Group',
    name: 'Non-Core Division Divestiture',
    narrative: 'Divest underperforming non-core business unit. Generates cash and allows focus on strategic priorities. May face valuation pressure in current market.',
    cost: 30,
    impactMagnitude: 3,
    introducedYear: 3,
    type: 'inorganic',
    guidingPrinciple: 'Cash optionality matters',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: true,
    revenueImpact: -0.02,
    recurringBenefit: 350,
  },
  {
    id: 'optimize-3-2',
    category: 'optimize',
    subcategory: 'Factory of the Future',
    name: 'Energy Efficiency Program',
    narrative: 'Comprehensive energy efficiency upgrades across facilities. LED lighting, smart HVAC, and energy recovery systems. Strong ROI with added ESG benefits.',
    cost: 120,
    impactMagnitude: 3,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    cogsImpact: -0.012,
    recurringBenefit: 55,
  },
  {
    id: 'optimize-3-3',
    category: 'optimize',
    subcategory: 'Organizational Restructure',
    name: 'Workforce Right-Sizing',
    narrative: 'Reduce headcount through voluntary separation and selective layoffs in response to cost pressures. Immediate savings but risk of losing key talent.',
    cost: 100,
    impactMagnitude: 4,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: 'Cash optionality matters',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    sgaImpact: -0.025,
    cogsImpact: -0.01,
    recurringBenefit: 90,
  },
  {
    id: 'optimize-3-4',
    category: 'optimize',
    subcategory: 'Global Supply Chain Redesign',
    name: 'Inventory Optimization',
    narrative: 'Implement advanced inventory management to reduce working capital requirements. Risk of stockouts during supply disruptions but significant cash release.',
    cost: 60,
    impactMagnitude: 2,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: 'Cash optionality matters',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    cogsImpact: -0.005,
    recurringBenefit: 40,
  },
  {
    id: 'optimize-3-5',
    category: 'optimize',
    subcategory: 'Select Group Transformation',
    name: 'Plant Footprint Rationalization',
    narrative: 'Close underutilized manufacturing facilities and consolidate production. Significant restructuring cost but lasting margin improvement.',
    cost: 200,
    impactMagnitude: 4,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    cogsImpact: -0.025,
    recurringBenefit: 120,
  },

  // ===== ROUND 4 =====
  {
    id: 'optimize-4-1',
    category: 'optimize',
    subcategory: 'Divest Group',
    name: 'Strategic Asset Sale',
    narrative: 'Sell non-strategic real estate and equipment at recession-impacted valuations. Generates needed liquidity but may sell below intrinsic value.',
    cost: 20,
    impactMagnitude: 2,
    introducedYear: 4,
    type: 'inorganic',
    guidingPrinciple: 'Cash optionality matters',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: true,
    recurringBenefit: 200,
  },
  {
    id: 'optimize-4-2',
    category: 'optimize',
    subcategory: 'Organizational Restructure',
    name: 'Deep Cost Restructuring',
    narrative: 'Aggressive cost reduction program across all functions. Difficult decisions but necessary for survival in prolonged downturn. Risk of capability damage.',
    cost: 150,
    impactMagnitude: 5,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: 'Cash optionality matters',
    isRisky: true,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    sgaImpact: -0.04,
    cogsImpact: -0.02,
    recurringBenefit: 150,
  },
  {
    id: 'optimize-4-3',
    category: 'optimize',
    subcategory: 'SG&A Optimization',
    name: 'Working from Home Optimization',
    narrative: 'Make remote work permanent for applicable roles. Reduce office space and associated costs. Maintains productivity while cutting real estate expenses.',
    cost: 40,
    impactMagnitude: 2,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    sgaImpact: -0.015,
    recurringBenefit: 35,
  },
  {
    id: 'optimize-4-4',
    category: 'optimize',
    subcategory: 'Global Supply Chain Redesign',
    name: 'Supplier Renegotiation Program',
    narrative: 'Leverage recession conditions to renegotiate supplier contracts. Risk of supplier relationship damage but significant cost reduction opportunity.',
    cost: 30,
    impactMagnitude: 3,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    cogsImpact: -0.015,
    recurringBenefit: 60,
  },
  {
    id: 'optimize-4-5',
    category: 'optimize',
    subcategory: 'Enterprise Digital Transformation',
    name: 'Process Automation Acceleration',
    narrative: 'Accelerate robotic process automation for administrative tasks. Reduced headcount needs align with downturn-driven workforce reduction.',
    cost: 80,
    impactMagnitude: 2,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    sgaImpact: -0.012,
    recurringBenefit: 45,
  },

  // ===== ROUND 5 =====
  {
    id: 'optimize-5-1',
    category: 'optimize',
    subcategory: 'Factory of the Future',
    name: 'Full Smart Factory Rollout',
    narrative: 'Expand proven smart factory technologies across global manufacturing footprint. Recovery positions for investment. Strong ROI from scale.',
    cost: 300,
    impactMagnitude: 4,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    cogsImpact: -0.025,
    recurringBenefit: 130,
  },
  {
    id: 'optimize-5-2',
    category: 'optimize',
    subcategory: 'Select Group Transformation',
    name: 'Business Unit Integration',
    narrative: 'Consolidate related business units for synergies and simplified structure. Restructuring costs but significant ongoing savings from eliminated redundancies.',
    cost: 160,
    impactMagnitude: 3,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    sgaImpact: -0.015,
    cogsImpact: -0.01,
    recurringBenefit: 85,
  },
  {
    id: 'optimize-5-3',
    category: 'optimize',
    subcategory: 'SG&A Optimization',
    name: 'Sales Force Effectiveness',
    narrative: 'Restructure sales organization with CRM tools and analytics. Improve customer coverage while reducing headcount. Better data-driven account management.',
    cost: 90,
    impactMagnitude: 2,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    sgaImpact: -0.01,
    recurringBenefit: 40,
  },
  {
    id: 'optimize-5-4',
    category: 'optimize',
    subcategory: 'Global Supply Chain Redesign',
    name: 'Near-Shoring Initiative',
    narrative: 'Shift supply chain closer to end markets. Higher unit costs offset by reduced logistics, inventory, and disruption risk. Resilience investment.',
    cost: 200,
    impactMagnitude: 3,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    cogsImpact: 0.005,
    riskPrevention: 'supply_chain_disruption',
    recurringBenefit: 50,
  },
  {
    id: 'optimize-5-5',
    category: 'optimize',
    subcategory: 'Enterprise Digital Transformation',
    name: 'AI Operations Platform',
    narrative: 'Deploy AI-powered operations management platform. Advanced demand forecasting, production scheduling, and quality prediction. Next-level efficiency.',
    cost: 180,
    impactMagnitude: 3,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    cogsImpact: -0.015,
    sgaImpact: -0.008,
    recurringBenefit: 75,
  },
];

// =============================================================================
// SUSTAIN DECISIONS (25 total - 5 per round)
// =============================================================================

const SUSTAIN_DECISIONS: Decision[] = [
  // ===== ROUND 1 =====
  {
    id: 'sustain-1-1',
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'Cybersecurity Enhancement',
    narrative: 'Comprehensive cybersecurity upgrade across IT infrastructure. Essential protection against growing cyber threats. No direct return but prevents catastrophic risk.',
    cost: 80,
    impactMagnitude: 2,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'cyber_attack',
    recurringBenefit: 0,
  },
  {
    id: 'sustain-1-2',
    category: 'sustain',
    subcategory: 'Talent & Leadership Upskilling',
    name: 'Technical Talent Development',
    narrative: 'Investment in training and development for engineering workforce. Essential to maintain competitive capabilities. Retention and capability building.',
    cost: 60,
    impactMagnitude: 2,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Position for recovery',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    recurringBenefit: 20,
  },
  {
    id: 'sustain-1-3',
    category: 'sustain',
    subcategory: 'Capital allocation strategy (maintenance)',
    name: 'Equipment Refresh Program',
    narrative: 'Scheduled replacement of aging manufacturing equipment. Maintains reliability and quality. Deferred investment risks production disruptions.',
    cost: 150,
    impactMagnitude: 3,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Cash optionality matters',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'equipment_failure',
    recurringBenefit: 25,
  },
  {
    id: 'sustain-1-4',
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'Environmental Compliance Investment',
    narrative: 'Proactive investment to meet upcoming environmental regulations. Mandatory compliance but early investment avoids rushed future spending.',
    cost: 100,
    impactMagnitude: 2,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'regulatory_penalty',
    recurringBenefit: 15,
  },
  {
    id: 'sustain-1-5',
    category: 'sustain',
    subcategory: 'Portfolio management (maintenance)',
    name: 'Customer Diversification Initiative',
    narrative: 'Sales effort to reduce concentration with top customers. Protects against customer-specific disruptions. Investment in sales coverage and relationship building.',
    cost: 50,
    impactMagnitude: 2,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    riskPrevention: 'key_customer_loss',
    recurringBenefit: 30,
  },

  // ===== ROUND 2 =====
  {
    id: 'sustain-2-1',
    category: 'sustain',
    subcategory: 'Talent & Leadership Upskilling',
    name: 'Leadership Development Program',
    narrative: 'Comprehensive leadership development for high-potential managers. Builds succession pipeline and organizational capability. Long-term investment in human capital.',
    cost: 70,
    impactMagnitude: 2,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: 'Position for recovery',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    recurringBenefit: 25,
  },
  {
    id: 'sustain-2-2',
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'Quality Management System Upgrade',
    narrative: 'Upgrade quality management systems to meet evolving OEM requirements. Essential for maintaining key customer relationships. Prevents costly quality escapes.',
    cost: 90,
    impactMagnitude: 2,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'quality_failure',
    recurringBenefit: 20,
  },
  {
    id: 'sustain-2-3',
    category: 'sustain',
    subcategory: 'Capital allocation strategy (maintenance)',
    name: 'IT Infrastructure Modernization',
    narrative: 'Update core IT systems and infrastructure. Addresses technical debt and security vulnerabilities. Foundational investment enabling future digital initiatives.',
    cost: 110,
    impactMagnitude: 2,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: 'Cash optionality matters',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'system_failure',
    recurringBenefit: 30,
  },
  {
    id: 'sustain-2-4',
    category: 'sustain',
    subcategory: 'Portfolio management (maintenance)',
    name: 'Supplier Relationship Investment',
    narrative: 'Strengthen relationships with strategic suppliers through joint development and long-term agreements. Improves supply security and preferential allocation.',
    cost: 40,
    impactMagnitude: 2,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'supply_chain_disruption',
    recurringBenefit: 20,
  },
  {
    id: 'sustain-2-5',
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'Health & Safety Investment',
    narrative: 'Enhanced workplace safety equipment and training programs. Essential for employee welfare and regulatory compliance. Reduces accident-related costs.',
    cost: 55,
    impactMagnitude: 1,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: 'Cash optionality matters',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'safety_incident',
    recurringBenefit: 15,
  },

  // ===== ROUND 3 =====
  {
    id: 'sustain-3-1',
    category: 'sustain',
    subcategory: 'Capital allocation strategy (maintenance)',
    name: 'Critical Equipment Maintenance',
    narrative: 'Essential maintenance program for production-critical equipment. Tempting to defer during cost pressure but failure would be catastrophic.',
    cost: 120,
    impactMagnitude: 3,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: 'Cash optionality matters',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'equipment_failure',
    recurringBenefit: 30,
  },
  {
    id: 'sustain-3-2',
    category: 'sustain',
    subcategory: 'Talent & Leadership Upskilling',
    name: 'Key Talent Retention Program',
    narrative: 'Targeted retention incentives for critical technical and leadership talent. Important to maintain during cost pressures when competitors may poach.',
    cost: 80,
    impactMagnitude: 3,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: 'Position for recovery',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'talent_loss',
    recurringBenefit: 25,
  },
  {
    id: 'sustain-3-3',
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'Business Continuity Enhancement',
    narrative: 'Strengthen business continuity planning and backup capabilities. Particularly important as risks increase during economic uncertainty.',
    cost: 65,
    impactMagnitude: 2,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'business_disruption',
    recurringBenefit: 15,
  },
  {
    id: 'sustain-3-4',
    category: 'sustain',
    subcategory: 'Portfolio management (maintenance)',
    name: 'Contract Renewal Defense',
    narrative: 'Proactive customer engagement to secure contract renewals during competitive environment. Prevents revenue loss from customer defection.',
    cost: 45,
    impactMagnitude: 2,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'key_customer_loss',
    recurringBenefit: 35,
  },
  {
    id: 'sustain-3-5',
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'Insurance Coverage Upgrade',
    narrative: 'Enhance insurance coverage for key operational and financial risks. Higher premiums but better protection against tail risks during uncertain times.',
    cost: 35,
    impactMagnitude: 1,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: 'Cash optionality matters',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'catastrophic_loss',
    recurringBenefit: 10,
  },

  // ===== ROUND 4 =====
  {
    id: 'sustain-4-1',
    category: 'sustain',
    subcategory: 'Capital allocation strategy (maintenance)',
    name: 'Minimum Viable Maintenance',
    narrative: 'Bare minimum maintenance investment to keep operations running. Risk of equipment failure but preserves cash during severe downturn.',
    cost: 80,
    impactMagnitude: 2,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: 'Cash optionality matters',
    isRisky: true,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'equipment_failure',
    recurringBenefit: 15,
  },
  {
    id: 'sustain-4-2',
    category: 'sustain',
    subcategory: 'Talent & Leadership Upskilling',
    name: 'Core Team Preservation',
    narrative: 'Investment to retain absolutely critical talent through recession. Skeletal but essential team for recovery. Others may be rehired post-downturn.',
    cost: 60,
    impactMagnitude: 3,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: 'Position for recovery',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'talent_loss',
    recurringBenefit: 20,
  },
  {
    id: 'sustain-4-3',
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'Regulatory Compliance Baseline',
    narrative: 'Minimum investment to maintain regulatory compliance. Cannot be deferred regardless of economic conditions. Non-discretionary.',
    cost: 70,
    impactMagnitude: 2,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: 'Cash optionality matters',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'regulatory_penalty',
    recurringBenefit: 10,
  },
  {
    id: 'sustain-4-4',
    category: 'sustain',
    subcategory: 'Portfolio management (maintenance)',
    name: 'Customer Relationship Triage',
    narrative: 'Focus relationship investment on most strategic customers. Accept some customer attrition to preserve resources for highest-value relationships.',
    cost: 30,
    impactMagnitude: 2,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'key_customer_loss',
    recurringBenefit: 25,
  },
  {
    id: 'sustain-4-5',
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'Financial Risk Management',
    narrative: 'Enhanced treasury and financial risk management during volatile conditions. Hedge exposures and manage liquidity carefully.',
    cost: 25,
    impactMagnitude: 2,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: 'Cash optionality matters',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'financial_risk',
    recurringBenefit: 15,
  },

  // ===== ROUND 5 =====
  {
    id: 'sustain-5-1',
    category: 'sustain',
    subcategory: 'Capital allocation strategy (maintenance)',
    name: 'Deferred Maintenance Catch-Up',
    narrative: 'Address deferred maintenance from recession period. Essential to restore equipment reliability for recovery. May require higher spend than normal.',
    cost: 180,
    impactMagnitude: 3,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: 'Position for recovery',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'equipment_failure',
    recurringBenefit: 40,
  },
  {
    id: 'sustain-5-2',
    category: 'sustain',
    subcategory: 'Talent & Leadership Upskilling',
    name: 'Workforce Rebuilding Program',
    narrative: 'Rehire and retrain workforce for recovery volumes. Compete for talent returning to job market. Investment in recruiting and onboarding.',
    cost: 100,
    impactMagnitude: 3,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: 'Position for recovery',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    recurringBenefit: 35,
  },
  {
    id: 'sustain-5-3',
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'ESG & Sustainability Investment',
    narrative: 'Comprehensive ESG program to meet growing stakeholder expectations. Carbon reduction, sustainable materials, and governance enhancement.',
    cost: 120,
    impactMagnitude: 2,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    riskPrevention: 'esg_risk',
    recurringBenefit: 30,
  },
  {
    id: 'sustain-5-4',
    category: 'sustain',
    subcategory: 'Portfolio management (maintenance)',
    name: 'Customer Win-Back Program',
    narrative: 'Re-engage customers lost during recession. Competitive offers and service improvements to rebuild market position.',
    cost: 75,
    impactMagnitude: 2,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: 'Position for recovery',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    revenueImpact: 0.01,
    recurringBenefit: 45,
  },
  {
    id: 'sustain-5-5',
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'Post-Crisis Risk Assessment',
    narrative: 'Comprehensive review and update of risk management framework based on lessons learned. Prepare for next downturn while positioned for recovery.',
    cost: 40,
    impactMagnitude: 1,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'business_disruption',
    recurringBenefit: 20,
  },
];

// =============================================================================
// EXPORTS
// =============================================================================

/** All 75 decision cards */
export const ALL_DECISIONS: Decision[] = [
  ...GROW_DECISIONS,
  ...OPTIMIZE_DECISIONS,
  ...SUSTAIN_DECISIONS,
];

/**
 * Get decisions available for a specific round
 * Returns 15 decisions (5 per category)
 */
export function getDecisionsForRound(round: RoundNumber): Decision[] {
  return ALL_DECISIONS.filter(d => d.introducedYear === round);
}

/**
 * Get decisions by category
 */
export function getDecisionsByCategory(category: 'grow' | 'optimize' | 'sustain'): Decision[] {
  return ALL_DECISIONS.filter(d => d.category === category);
}

/**
 * Get a single decision by ID
 */
export function getDecisionById(id: string): Decision | undefined {
  return ALL_DECISIONS.find(d => d.id === id);
}

/**
 * Get all risky decisions
 */
export function getRiskyDecisions(): Decision[] {
  return ALL_DECISIONS.filter(d => d.isRisky);
}

/**
 * Validate that we have exactly 75 decisions (25 per category, 5 per round)
 */
export function validateDecisionConfiguration(): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  
  // Check total count
  if (ALL_DECISIONS.length !== 75) {
    errors.push(`Expected 75 decisions, found ${ALL_DECISIONS.length}`);
  }
  
  // Check category counts
  const categories = ['grow', 'optimize', 'sustain'] as const;
  for (const category of categories) {
    const count = ALL_DECISIONS.filter(d => d.category === category).length;
    if (count !== 25) {
      errors.push(`Category '${category}' has ${count} decisions, expected 25`);
    }
  }
  
  // Check round distribution
  for (let round = 1; round <= 5; round++) {
    const roundDecisions = getDecisionsForRound(round as RoundNumber);
    if (roundDecisions.length !== 15) {
      errors.push(`Round ${round} has ${roundDecisions.length} decisions, expected 15`);
    }
    
    // Check category distribution within round
    for (const category of categories) {
      const count = roundDecisions.filter(d => d.category === category).length;
      if (count !== 5) {
        errors.push(`Round ${round} category '${category}' has ${count} decisions, expected 5`);
      }
    }
  }
  
  // Check for duplicate IDs
  const ids = ALL_DECISIONS.map(d => d.id);
  const uniqueIds = new Set(ids);
  if (uniqueIds.size !== ids.length) {
    errors.push('Duplicate decision IDs found');
  }
  
  return {
    valid: errors.length === 0,
    errors,
  };
}
