/**
 * Value Creation Simulation - Decision Cards Configuration
 * Loads decisions from public/decisions.json (generated by scripts/import-decisions-from-csv.mjs from your CSV).
 * Single source of truth: both demo (frontend) and live game (backend) use that file.
 *
 * To update cards: replace decision_cards_export.csv and run:
 *   node scripts/import-decisions-from-csv.mjs
 * Then restart the backend.
 */

import { readFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import type { Decision, RoundNumber } from '../types/game.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const fromCwd = join(process.cwd(), 'public', 'decisions.json');
const fromBackend = join(__dirname, '..', '..', 'public', 'decisions.json');
const fromDist = join(__dirname, '..', '..', '..', 'public', 'decisions.json');

function loadDecisions(): Decision[] {
  const path =
    process.env.DECISIONS_JSON_PATH ||
    (existsSync(fromCwd) ? fromCwd : existsSync(fromDist) ? fromDist : existsSync(fromBackend) ? fromBackend : fromDist);
  if (!existsSync(path)) {
    console.warn('[decisions] JSON not found. Tried:', fromCwd, fromDist, fromBackend, '- run: node scripts/import-decisions-from-csv.mjs');
    return [];
  }
  const raw = readFileSync(path, 'utf8');
  const parsed = JSON.parse(raw) as unknown;
  if (!Array.isArray(parsed)) {
    console.warn('[decisions] Invalid JSON: expected array');
    return [];
  }
  return parsed as Decision[];
}

/** All decision cards; loaded from public/decisions.json at module load */
export const ALL_DECISIONS: Decision[] = loadDecisions();

/**
 * Get decisions available for a specific round
 */
export function getDecisionsForRound(round: RoundNumber): Decision[] {
  return ALL_DECISIONS.filter((d) => d.introducedYear === round);
}

/**
 * Get decisions by category
 */
export function getDecisionsByCategory(category: 'grow' | 'optimize' | 'sustain'): Decision[] {
  return ALL_DECISIONS.filter((d) => d.category === category);
}

/**
 * Get a single decision by ID
 */
export function getDecisionById(id: string): Decision | undefined {
  return ALL_DECISIONS.find((d) => d.id === id);
}

/**
 * Validate decision configuration
 */
export function validateDecisionConfiguration(): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  if (ALL_DECISIONS.length < 75) {
    errors.push(`Expected at least 75 decisions, found ${ALL_DECISIONS.length}. Run: node scripts/import-decisions-from-csv.mjs`);
  }
  for (let round = 1; round <= 5; round++) {
    const roundDecisions = getDecisionsForRound(round as RoundNumber);
    if (roundDecisions.length < 12) {
      errors.push(`Round ${round} has only ${roundDecisions.length} decisions, expected at least 12`);
    }
  }
  const ids = ALL_DECISIONS.map((d) => d.id);
  const uniqueIds = new Set(ids);
  if (uniqueIds.size !== ids.length) {
    const duplicates = ids.filter((id, index) => ids.indexOf(id) !== index);
    errors.push(`Duplicate decision IDs found: ${duplicates.join(', ')}`);
  }
  return {
    valid: errors.length === 0,
    errors,
  };
}
