/**
 * Value Creation Simulation - Decision Cards Configuration
 * 75 total decision cards: Based on Excel Decisions tab (rows 2–76).
 * Card content: A = decision #, F = name, G = detail (narrative).
 * Grow back: AA, Y, Z, AB, AC. Optimize back: AF, AG, AE, AH. Sustain back: AK, AL, AJ, AM.
 */

import type { Decision, RoundNumber, GrowMetrics, OptimizeMetrics, SustainMetrics } from '../types/game.js';

// =============================================================================
// GROW DECISIONS (Based on Excel - Lever = "Grow")
// =============================================================================

const GROW_DECISIONS: Decision[] = [
  // ===== ROUND 1 =====
  {
    id: 'grow-1-1',
    decisionNumber: 1,
    category: 'grow',
    subcategory: 'Expand Manufacturing Footprint',
    name: 'Mexico Capacity Expansion',
    narrative: 'Expand existing Mexican operations to increase capacity for North American OEMs. Nearshoring trend favors this investment with relatively predictable returns.',
    cost: 800,
    impactMagnitude: 3,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.02,
    recurringBenefit: 80,
    growMetrics: {
      revenue1Year: 1600,
      fiveYearGrowth: 5,
      investmentsTotal: 800,
      investmentPeriod: 2,
      ebitMargin: 11,
    },

  },
  {
    id: 'grow-1-2',
    decisionNumber: 2,
    category: 'grow',
    subcategory: 'Scale R&D for Next-Gen Portfolio',
    name: 'Advanced Powertrain R&D Expansion',
    narrative: 'Invest in expanding R&D capabilities for next-generation vehicle powertrains and propulsion systems. This positions Magna to capture growing market share in advanced mobility but requires significant upfront investment with returns materializing over 2-3 years.',
    cost: 1000,
    impactMagnitude: 4,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.03,
    recurringBenefit: 150,
    growMetrics: {
      revenue1Year: 2000,
      fiveYearGrowth: 5,
      investmentsTotal: 1000,
      investmentPeriod: 3,
      ebitMargin: 11,
    },

  },
  {
    id: 'grow-1-3',
    decisionNumber: 3,
    category: 'grow',
    subcategory: 'Enter New Geography / Market',
    name: 'Southeast Asia Market Entry',
    narrative: 'Establish manufacturing presence in Thailand/Vietnam to serve growing ASEAN automotive market. Lower labor costs and proximity to emerging markets, but execution risk in new geography.',
    cost: 800,
    impactMagnitude: 3,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: true,
    durationYears: 2,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.025,
    recurringBenefit: 120,
    growMetrics: {
      revenue1Year: 1200,
      fiveYearGrowth: 3,
      investmentsTotal: 800,
      investmentPeriod: 2,
      ebitMargin: 5,
    },

  },
  {
    id: 'grow-1-4',
    decisionNumber: 4,
    category: 'grow',
    subcategory: 'JV / Strategic Partnership',
    name: 'Battery Technology JV',
    narrative: 'Form joint venture with battery cell manufacturer to secure supply and develop integrated battery systems. Strategic hedge against vertical integration by OEMs.',
    cost: 1000,
    impactMagnitude: 4,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: '3. Stay flexible',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.035,
    recurringBenefit: 140,
    growMetrics: {
      revenue1Year: 800,
      fiveYearGrowth: 0,
      investmentsTotal: 1000,
      investmentPeriod: 2,
      ebitMargin: 10,
    },

  },
  {
    id: 'grow-1-5',
    decisionNumber: 5,
    category: 'grow',
    subcategory: 'Expand Manufacturing Footprint',
    name: 'Concentrated OEM Capacity Investment',
    narrative: 'Major capacity investment for an OEM\'s flagship vehicle program. The OEM has committed to unprecedented volumes and offered favorable terms for exclusive supply. Higher projected returns than diversified approach, with dedicated production lines and simpler logistics.',
    cost: 1000,
    impactMagnitude: 4,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,  // Not flagged as risky - that's the trap!
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    revenueImpact: 0.028,
    recurringBenefit: 120,
    // NOTE: This decision's returns go to $0 when OEM Program Cancellation event triggers
    vulnerableTo: 'oem_program_cancellation',
    growMetrics: {
      revenue1Year: 1500,
      fiveYearGrowth: 3,
      investmentsTotal: 1000,
      investmentPeriod: 2,
      ebitMargin: 5,
    },

  },

  // ===== ROUND 2 =====
  {
    id: 'grow-2-1',
    decisionNumber: 16,
    category: 'grow',
    subcategory: 'Launch a New Business',
    name: 'Autonomous Driving Systems Unit',
    narrative: 'Launch dedicated business unit for advanced driver assistance systems (ADAS) and autonomous driving technology. High potential but uncertain returns as technology evolves rapidly.',
    cost: 1000,
    impactMagnitude: 5,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: true,
    durationYears: 2,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.04,
    recurringBenefit: 180,
    growMetrics: {
      revenue1Year: 800,
      fiveYearGrowth: 0,
      investmentsTotal: 1000,
      investmentPeriod: 2,
      ebitMargin: 10,
    },

  },
  {
    id: 'grow-2-2',
    decisionNumber: 17,
    category: 'grow',
    subcategory: 'Expand Manufacturing Footprint',
    name: 'Diversified OEM Capacity Investment',
    narrative: 'Invest in flexible powertrain manufacturing capacity additions across existing facilities globally to serve multiple OEM customers. Spreads investment across GM, Ford, Honda, and BMW programs. Lower per-unit returns but diversified risk exposure. Requires more coordination but provides insurance against customer-specific disruptions.',
    cost: 800,
    impactMagnitude: 3,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: '3. Stay flexible',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.018,
    recurringBenefit: 80,
    riskPrevention: 'oem_program_cancellation',
    growMetrics: {
      revenue1Year: 1600,
      fiveYearGrowth: 0,
      investmentsTotal: 800,
      investmentPeriod: 2,
      ebitMargin: 6,
    },

  },
  {
    id: 'grow-2-3',
    decisionNumber: 18,
    category: 'grow',
    subcategory: 'Acquire a Business',
    name: 'Bolt-on Sensor Acquisition',
    narrative: 'Acquire small sensor technology company to enhance ADAS capabilities. Adds specialized engineering talent and IP. Integration risk exists but accelerates time-to-market.',
    cost: 0,
    impactMagnitude: 3,
    introducedYear: 2,
    type: 'inorganic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.015,
    recurringBenefit: 70,
    growMetrics: {
      revenue1Year: 2000,
      fiveYearGrowth: 10,
      investmentsTotal: 0,
      investmentPeriod: 0,
      ebitMargin: 11,
    },

  },
  {
    id: 'grow-2-4',
    decisionNumber: 19,
    category: 'grow',
    subcategory: 'Platform-Level Technology Bets',
    name: 'Software-Defined Vehicle Platform',
    narrative: 'Make a targeted technology bet on modular, software-defined vehicle architectures, reflecting OEM demand for faster feature deployment, lower lifecycle cost, and vendor-agnostic platforms.',
    cost: 1000,
    impactMagnitude: 5,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: true,
    durationYears: 2,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.05,
    recurringBenefit: 200,
    growMetrics: {
      revenue1Year: 800,
      fiveYearGrowth: 0,
      investmentsTotal: 1000,
      investmentPeriod: 2,
      ebitMargin: 10,
    },

  },
  {
    id: 'grow-2-5',
    decisionNumber: 20,
    category: 'grow',
    subcategory: 'Expand Manufacturing Footprint',
    name: 'European Advanced Assembly Facility',
    narrative: 'Build dedicated advanced vehicle assembly plant in Eastern Europe. Positions for European regulatory requirements and next-gen vehicle platforms. Significant investment with long payback period.',
    cost: 1000,
    impactMagnitude: 4,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: '3. Stay flexible',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.04,
    recurringBenefit: 160,
    growMetrics: {
      revenue1Year: 1500,
      fiveYearGrowth: 3,
      investmentsTotal: 1000,
      investmentPeriod: 3,
      ebitMargin: 5,
    },

  },

  // ===== ROUND 3 =====
  {
    id: 'grow-3-1',
    decisionNumber: 31,
    category: 'grow',
    subcategory: 'Expand Manufacturing Footprint',
    name: 'North America Advanced Component Hub',
    narrative: 'Consolidate advanced component manufacturing across business units into a single, dedicated cross-group facility, capturing scale efficiencies and capability depth while requiring a significant fixed-asset commitment amid uncertain market demand.',
    cost: 1000,
    impactMagnitude: 4,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.035,
    recurringBenefit: 140,
    growMetrics: {
      revenue1Year: 1500,
      fiveYearGrowth: 3,
      investmentsTotal: 1000,
      investmentPeriod: 1,
      ebitMargin: 5,
    },

  },
  {
    id: 'grow-3-2',
    decisionNumber: 32,
    category: 'grow',
    subcategory: 'JV / Strategic Partnership',
    name: 'Chinese OEM Partnership',
    narrative: 'Strategic partnership with leading Chinese automotive manufacturer. Access to largest automotive growth market but geopolitical and IP concerns. High reward potential with elevated risk.',
    cost: 1000,
    impactMagnitude: 4,
    introducedYear: 3,
    type: 'inorganic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: true,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.05,
    recurringBenefit: 180,
    growMetrics: {
      revenue1Year: 1500,
      fiveYearGrowth: 3,
      investmentsTotal: 1000,
      investmentPeriod: 1,
      ebitMargin: 5,
    },

  },
  {
    id: 'grow-3-3',
    decisionNumber: 33,
    category: 'grow',
    subcategory: 'Acquire a Business',
    name: 'Distressed Competitor Acquisition',
    narrative: 'Opportunity to acquire struggling competitor at attractive valuation. Significant capacity and customer relationships, but integration complexity and some legacy issues.',
    cost: 0,
    impactMagnitude: 5,
    introducedYear: 3,
    type: 'inorganic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: true,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.08,
    recurringBenefit: 250,
    growMetrics: {
      revenue1Year: 8000,
      fiveYearGrowth: 10,
      investmentsTotal: 0,
      investmentPeriod: 0,
      ebitMargin: 11,
    },

  },
  {
    id: 'grow-3-4',
    decisionNumber: 34,
    category: 'grow',
    subcategory: 'Scale R&D for Next-Gen Portfolio',
    name: 'Solid-State Battery Research',
    narrative: 'Invest in next-generation solid-state battery technology research. Could leapfrog current technology but commercialization timeline uncertain.',
    cost: 1000,
    impactMagnitude: 4,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: true,
    durationYears: 2,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.025,
    recurringBenefit: 120,
    growMetrics: {
      revenue1Year: 1500,
      fiveYearGrowth: 3,
      investmentsTotal: 1000,
      investmentPeriod: 1,
      ebitMargin: 5,
    },

  },
  {
    id: 'grow-3-5',
    decisionNumber: 35,
    category: 'grow',
    subcategory: 'Revenue Diversification',
    name: 'Expand Beyond OEMs into Non-Traditional Customers',
    narrative: 'Pursue revenue opportunities with non-OEM customers (e.g., Amazon, fleet operators, mobility platforms) by adapting Magna\'s manufacturing and engineering capabilities to adjacent use cases.',
    cost: 600,
    impactMagnitude: 3,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.02,
    recurringBenefit: 90,
    growMetrics: {
      revenue1Year: 900,
      fiveYearGrowth: 3,
      investmentsTotal: 600,
      investmentPeriod: 1,
      ebitMargin: 5,
    },

  },

  // ===== ROUND 4 =====
  {
    id: 'grow-4-1',
    decisionNumber: 46,
    category: 'grow',
    subcategory: 'Acquire a Business',
    name: 'Opportunistic Acquisition - Premium Supplier',
    narrative: 'Rare opportunity to acquire premium supplier at recession-driven valuation. Strong customer relationships and margins. Requires significant capital during challenging times.',
    cost: 0,
    impactMagnitude: 5,
    introducedYear: 4,
    type: 'inorganic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.07,
    recurringBenefit: 280,
    growMetrics: {
      revenue1Year: 8000,
      fiveYearGrowth: 10,
      investmentsTotal: 0,
      investmentPeriod: 0,
      ebitMargin: 11,
    },

  },
  {
    id: 'grow-4-2',
    decisionNumber: 47,
    category: 'grow',
    subcategory: 'Pricing Strategy',
    name: 'Aggressive pricing to win new business',
    narrative: 'Pursue new business using aggressive pricing mechanisms, accepting near-term dilution to drive volume growth and market entry.',
    cost: 800,
    impactMagnitude: 3,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: true,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    revenueImpact: 0.03,
    recurringBenefit: 60,
    cogsImpact: 0.01, // Slightly higher costs due to aggressive pricing
    growMetrics: {
      revenue1Year: 640,
      fiveYearGrowth: 0,
      investmentsTotal: 800,
      investmentPeriod: 2,
      ebitMargin: 10,
    },

  },
  {
    id: 'grow-4-3',
    decisionNumber: 48,
    category: 'grow',
    subcategory: 'Enter New Geography / Market',
    name: 'Middle East Manufacturing Partnership',
    narrative: 'Partnership with Gulf state sovereign wealth fund for new manufacturing hub. Diversifies geographic exposure and provides capital, but execution complexity.',
    cost: 800,
    impactMagnitude: 3,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.02,
    recurringBenefit: 90,
    growMetrics: {
      revenue1Year: 1200,
      fiveYearGrowth: 3,
      investmentsTotal: 800,
      investmentPeriod: 2,
      ebitMargin: 5,
    },

  },
  {
    id: 'grow-4-4',
    decisionNumber: 49,
    category: 'grow',
    subcategory: 'JV / Strategic Partnership',
    name: 'Hydrogen Fuel Cell Alliance',
    narrative: 'Join consortium developing hydrogen fuel cell technology for commercial vehicles. Hedges powertrain technology bets but requires ongoing investment with uncertain payoff timeline.',
    cost: 600,
    impactMagnitude: 2,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: true,
    durationYears: 2,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.01,
    recurringBenefit: 50,
    growMetrics: {
      revenue1Year: 1200,
      fiveYearGrowth: 0,
      investmentsTotal: 600,
      investmentPeriod: 2,
      ebitMargin: 6,
    },

  },
  {
    id: 'grow-4-5',
    decisionNumber: 50,
    category: 'grow',
    subcategory: 'Expand Manufacturing Footprint',
    name: 'Underutilized Capacity Purchase',
    narrative: 'Purchase underutilized manufacturing facility from distressed competitor at significant discount. Ready infrastructure but requires investment to modernize.',
    cost: 800,
    impactMagnitude: 3,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.025,
    recurringBenefit: 100,
    growMetrics: {
      revenue1Year: 1200,
      fiveYearGrowth: 3,
      investmentsTotal: 800,
      investmentPeriod: 2,
      ebitMargin: 5,
    },

  },

  // ===== ROUND 5 =====
  {
    id: 'grow-5-1',
    decisionNumber: 61,
    category: 'grow',
    subcategory: 'Commercial Prioritization',
    name: 'Prioritize Commercial Recoveries to win business',
    narrative: 'Leverage commercial recoveries as negotiation tools to win new business, using offset economics to secure contracts while remaining net-accretive.',
    cost: 800,
    impactMagnitude: 2,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: '2. Cash is king',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    revenueImpact: 0.015,
    recurringBenefit: 50,
    growMetrics: {
      revenue1Year: 1600,
      fiveYearGrowth: 5,
      investmentsTotal: 800,
      investmentPeriod: 2,
      ebitMargin: 11,
    },

  },
  {
    id: 'grow-5-2',
    decisionNumber: 62,
    category: 'grow',
    subcategory: 'Expand Manufacturing Footprint',
    name: 'Global Capacity Expansion Program',
    narrative: 'Comprehensive capacity expansion across multiple regions to meet recovering demand. Significant investment but positions for sustainable growth trajectory.',
    cost: 1000,
    impactMagnitude: 5,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.06,
    recurringBenefit: 240,
    growMetrics: {
      revenue1Year: 800,
      fiveYearGrowth: 0,
      investmentsTotal: 1000,
      investmentPeriod: 2,
      ebitMargin: 10,
    },

  },
  {
    id: 'grow-5-3',
    decisionNumber: 63,
    category: 'grow',
    subcategory: 'Acquire a Business',
    name: 'Strategic Technology Acquisition',
    narrative: 'Acquire emerging technology company with breakthrough thermal management system for advanced vehicles. Positions for next-generation vehicle requirements. Premium valuation as market recovers.',
    cost: 0,
    impactMagnitude: 4,
    introducedYear: 5,
    type: 'inorganic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.03,
    recurringBenefit: 130,
    growMetrics: {
      revenue1Year: 4000,
      fiveYearGrowth: 10,
      investmentsTotal: 0,
      investmentPeriod: 0,
      ebitMargin: 11,
    },

  },
  {
    id: 'grow-5-4',
    decisionNumber: 64,
    category: 'grow',
    subcategory: 'JV / Strategic Partnership',
    name: 'OEM Strategic Alliance',
    narrative: 'Deep strategic partnership with major OEM for exclusive supply arrangements. Secures significant volume but concentration risk. Attractive terms as OEM seeks reliable supplier.',
    cost: 1000,
    impactMagnitude: 4,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    revenueImpact: 0.05,
    recurringBenefit: 200,
    growMetrics: {
      revenue1Year: 2000,
      fiveYearGrowth: 0,
      investmentsTotal: 1000,
      investmentPeriod: 2,
      ebitMargin: 6,
    },

  },
  {
    id: 'grow-5-5',
    decisionNumber: 65,
    category: 'grow',
    subcategory: 'Launch a New Business',
    name: 'Mobility Services Platform',
    narrative: 'Launch platform to support fleet operators and mobility-as-a-service providers. Diversifies revenue model and creates recurring revenue streams.',
    cost: 800,
    impactMagnitude: 3,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.02,
    recurringBenefit: 80,
    growMetrics: {
      revenue1Year: 1200,
      fiveYearGrowth: 3,
      investmentsTotal: 800,
      investmentPeriod: 1,
      ebitMargin: 5,
    },

  },
  {
    id: 'grow-5-6',
    decisionNumber: 66,
    category: 'grow',
    subcategory: 'Scale R&D for Next-Gen Portfolio',
    name: 'Next-Gen ADAS Development',
    narrative: 'Accelerate development of Level 4 autonomous driving capabilities. Recovery enables increased R&D spending. Positions for 2030s autonomous vehicle requirements.',
    cost: 1000,
    impactMagnitude: 4,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.04,
    recurringBenefit: 160,
    growMetrics: {
      revenue1Year: 2000,
      fiveYearGrowth: 5,
      investmentsTotal: 1000,
      investmentPeriod: 1,
      ebitMargin: 11,
    },

  },
];

// =============================================================================
// OPTIMIZE DECISIONS (Based on Excel - Lever = "Optimize")
// =============================================================================

const OPTIMIZE_DECISIONS: Decision[] = [
  // ===== ROUND 1 =====
  {
    id: 'optimize-1-1',
    decisionNumber: 6,
    category: 'optimize',
    subcategory: 'Factory of the Future',
    name: 'Smart Factory Pilot Program',
    narrative: 'Implement Industry 4.0 technologies in flagship facility. IoT sensors, AI-driven quality control, and predictive maintenance. Proof of concept for broader rollout.',
    cost: 120,
    impactMagnitude: 3,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    cogsImpact: -0.01,
    recurringBenefit: 60,
    optimizeMetrics: {
      implementationCost: 0,
      investment: 120,
      investmentPeriod: 2,
      annualCost: 40,
    },

  },
  {
    id: 'optimize-1-2',
    decisionNumber: 7,
    category: 'optimize',
    subcategory: 'SG&A Optimization',
    name: 'Shared Services Consolidation',
    narrative: 'Consolidate back-office functions (finance, HR, IT) into regional shared services centers. Upfront investment yields ongoing cost savings.',
    cost: 0,
    impactMagnitude: 2,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    sgaImpact: -0.02,
    recurringBenefit: 40,
    optimizeMetrics: {
      implementationCost: 2.5,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 40,
    },

  },
  {
    id: 'optimize-1-3',
    decisionNumber: 8,
    category: 'optimize',
    subcategory: 'Global Supply Chain Redesign',
    name: 'Supplier Dual-Sourcing Initiative',
    narrative: 'Establish secondary suppliers for critical components. Increases supply chain resilience and negotiating leverage. Small cost premium offset by risk reduction.',
    cost: 0,
    impactMagnitude: 3,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    cogsImpact: 0.005,
    riskPrevention: 'supply_chain_disruption',
    recurringBenefit: 30,
    optimizeMetrics: {
      implementationCost: 2,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 80,
    },

  },
  {
    id: 'optimize-1-4',
    decisionNumber: 9,
    category: 'optimize',
    subcategory: 'Enterprise Digital Transformation',
    name: 'ERP System Upgrade',
    narrative: 'Launch enterprise-wide Data & ERP Transformation, migrating core ERP to a modern cloud platform while redesigning data architecture, analytics, and end-to-end processes. Enables advanced analytics, AI-driven automation, and materially improved decision-making across the business.',
    cost: 120,
    impactMagnitude: 2,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: '2. Cash is king',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    sgaImpact: -0.01,
    cogsImpact: -0.005,
    recurringBenefit: 50,
    optimizeMetrics: {
      implementationCost: 0,
      investment: 120,
      investmentPeriod: 2,
      annualCost: 40,
    },

  },
  {
    id: 'optimize-1-5',
    decisionNumber: 10,
    category: 'optimize',
    subcategory: 'Organizational Restructure',
    name: 'Management Delayering',
    narrative: 'Execute a management reorganization to de-layer the organization, accelerating decision-making, clarifying accountability, and sustainably reducing overhead.',
    cost: 0,
    impactMagnitude: 2,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: '3. Stay flexible',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    sgaImpact: -0.015,
    recurringBenefit: 35,
    optimizeMetrics: {
      implementationCost: 1,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 40,
    },

  },

  // ===== ROUND 2 =====
  {
    id: 'optimize-2-1',
    decisionNumber: 21,
    category: 'optimize',
    subcategory: 'Enterprise Digital Transformation',
    name: 'Advanced Analytics Platform',
    narrative: 'Deploy enterprise analytics platform to improve decision-making across operations. Predictive insights for demand planning, quality, and maintenance.',
    cost: 0,
    impactMagnitude: 2,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    cogsImpact: -0.008,
    sgaImpact: -0.005,
    recurringBenefit: 50,
    optimizeMetrics: {
      implementationCost: 3,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 40,
    },

  },
  {
    id: 'optimize-2-2',
    decisionNumber: 22,
    category: 'optimize',
    subcategory: 'Factory of the Future',
    name: 'Automation Expansion Program',
    narrative: 'Expand robotic automation across manufacturing facilities. Higher upfront cost but significant labor cost reduction and quality improvement.',
    cost: 360,
    impactMagnitude: 4,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: '2. Cash is king',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    cogsImpact: -0.02,
    recurringBenefit: 100,
    optimizeMetrics: {
      implementationCost: 0,
      investment: 360,
      investmentPeriod: 1,
      annualCost: 120,
    },

  },
  {
    id: 'optimize-2-3',
    decisionNumber: 23,
    category: 'optimize',
    subcategory: 'Select Group Transformation',
    name: 'Underperforming Division Turnaround',
    narrative: 'Comprehensive operational improvement program for underperforming business unit. New leadership, process redesign, and targeted investments.',
    cost: 0,
    impactMagnitude: 3,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    cogsImpact: -0.015,
    sgaImpact: -0.01,
    recurringBenefit: 80,
    optimizeMetrics: {
      implementationCost: 3,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 80,
    },

  },
  {
    id: 'optimize-2-4',
    decisionNumber: 24,
    category: 'optimize',
    subcategory: 'Global Supply Chain Redesign',
    name: 'Logistics Network Optimization',
    narrative: 'Redesign global logistics network to reduce transportation costs and improve delivery times. Consolidate warehouses and optimize routes.',
    cost: 0,
    impactMagnitude: 3,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    cogsImpact: -0.01,
    recurringBenefit: 55,
    optimizeMetrics: {
      implementationCost: 3,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 80,
    },

  },
  {
    id: 'optimize-2-5',
    decisionNumber: 25,
    category: 'optimize',
    subcategory: 'SG&A Optimization',
    name: 'Procurement Excellence Program',
    narrative: 'Implement strategic sourcing and supplier management program. Leverage scale for better pricing and terms on indirect spend.',
    cost: 0,
    impactMagnitude: 2,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    sgaImpact: -0.01,
    cogsImpact: -0.005,
    recurringBenefit: 45,
    optimizeMetrics: {
      implementationCost: 3,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 40,
    },

  },

  // ===== ROUND 3 =====
  {
    id: 'optimize-3-1',
    decisionNumber: 36,
    category: 'optimize',
    subcategory: 'Divest Group',
    name: 'Non-Core Division Divestiture',
    narrative: 'Divest underperforming non-core business unit. Generates cash and allows focus on strategic priorities. May face valuation pressure in current market.',
    cost: 0,
    impactMagnitude: 3,
    introducedYear: 3,
    type: 'inorganic',
    guidingPrinciple: '2. Cash is king',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: true,
    revenueImpact: -0.02,
    recurringBenefit: 350,
    optimizeMetrics: {
      implementationCost: 0,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 0,
    },

  },
  {
    id: 'optimize-3-2',
    decisionNumber: 37,
    category: 'optimize',
    subcategory: 'Program Governance',
    name: 'Bypass Standard Launch Gates to Meet SOP Deadline',
    narrative: 'Streamline or bypass select internal approval and validation steps to meet OEM SOP deadlines and avoid penalties, accepting higher rework risk in exchange for schedule adherence and cost savings.',
    cost: 0,
    impactMagnitude: 2,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: '3. Stay flexible',
    isRisky: true, // Risk of quality issues
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    cogsImpact: -0.008,
    recurringBenefit: 30,
    optimizeMetrics: {
      implementationCost: 3,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 80,
    },

  },
  {
    id: 'optimize-3-3',
    decisionNumber: 38,
    category: 'optimize',
    subcategory: 'Factory of the Future',
    name: 'Energy Efficiency Program',
    narrative: 'Comprehensive energy efficiency upgrades across facilities. LED lighting, smart HVAC, and energy recovery systems. Strong ROI with added ESG benefits.',
    cost: 120,
    impactMagnitude: 3,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    cogsImpact: -0.012,
    recurringBenefit: 55,
    optimizeMetrics: {
      implementationCost: 0,
      investment: 120,
      investmentPeriod: 2,
      annualCost: 40,
    },

  },
  {
    id: 'optimize-3-4',
    decisionNumber: 39,
    category: 'optimize',
    subcategory: 'Organizational Restructure',
    name: 'Workforce Right-Sizing',
    narrative: 'Reduce headcount through voluntary separation and selective layoffs in response to cost pressures. Immediate savings but risk of losing key talent.',
    cost: 0,
    impactMagnitude: 4,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: '2. Cash is king',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    sgaImpact: -0.025,
    cogsImpact: -0.01,
    recurringBenefit: 90,
    optimizeMetrics: {
      implementationCost: 3,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 120,
    },

  },
  {
    id: 'optimize-3-5',
    decisionNumber: 40,
    category: 'optimize',
    subcategory: 'Select Group Transformation',
    name: 'Plant Footprint Rationalization',
    narrative: 'Close underutilized manufacturing facilities and consolidate production. Significant restructuring cost but lasting margin improvement.',
    cost: 0,
    impactMagnitude: 4,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    cogsImpact: -0.025,
    recurringBenefit: 120,
    optimizeMetrics: {
      implementationCost: 1.5,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 120,
    },

  },

  // ===== ROUND 4 =====
  {
    id: 'optimize-4-1',
    decisionNumber: 51,
    category: 'optimize',
    subcategory: 'Capital Timing',
    name: 'Material process flow automation',
    narrative: 'Execute material end-to-end process flow optimization, simplifying handoffs and eliminating waste to reduce cost, cycle time, and operational friction.',
    cost: 0,
    impactMagnitude: 2,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: '3. Stay flexible',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    cogsImpact: -0.01,
    recurringBenefit: 40,
    optimizeMetrics: {
      implementationCost: 3,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 40,
    },

  },
  {
    id: 'optimize-4-2',
    decisionNumber: 52,
    category: 'optimize',
    subcategory: 'Divest Group',
    name: 'Strategic Asset Sale',
    narrative: 'Sell non-strategic real estate and equipment at recession-impacted valuations. Generates needed liquidity but may sell below intrinsic value.',
    cost: 0,
    impactMagnitude: 2,
    introducedYear: 4,
    type: 'inorganic',
    guidingPrinciple: '2. Cash is king',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: true,
    recurringBenefit: 200,
    optimizeMetrics: {
      implementationCost: 0,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 0,
    },

  },
  {
    id: 'optimize-4-3',
    decisionNumber: 53,
    category: 'optimize',
    subcategory: 'SG&A Optimization',
    name: 'Working from Home Optimization',
    narrative: 'Make remote work permanent for applicable roles. Reduce office space and associated costs. Maintains productivity while cutting real estate expenses.',
    cost: 0,
    impactMagnitude: 2,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: '2. Cash is king',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    sgaImpact: -0.015,
    recurringBenefit: 35,
    optimizeMetrics: {
      implementationCost: 3,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 40,
    },

  },
  {
    id: 'optimize-4-4',
    decisionNumber: 54,
    category: 'optimize',
    subcategory: 'Global Supply Chain Redesign',
    name: 'Supplier Renegotiation Program',
    narrative: 'Leverage recession conditions to renegotiate supplier contracts. Risk of supplier relationship damage but significant cost reduction opportunity.',
    cost: 0,
    impactMagnitude: 3,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: '2. Cash is king',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    cogsImpact: -0.015,
    recurringBenefit: 60,
    optimizeMetrics: {
      implementationCost: 3,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 80,
    },

  },
  {
    id: 'optimize-4-5',
    decisionNumber: 55,
    category: 'optimize',
    subcategory: 'Enterprise Digital Transformation',
    name: 'Process Automation Acceleration',
    narrative: 'Accelerate robotic process automation for administrative tasks. Reduced headcount needs align with downturn-driven workforce reduction.',
    cost: 120,
    impactMagnitude: 2,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: '2. Cash is king',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    sgaImpact: -0.012,
    recurringBenefit: 45,
    optimizeMetrics: {
      implementationCost: 0,
      investment: 120,
      investmentPeriod: 1,
      annualCost: 40,
    },

  },

  // ===== ROUND 5 =====
  {
    id: 'optimize-5-1',
    decisionNumber: 67,
    category: 'optimize',
    subcategory: 'Enterprise Digital Transformation',
    name: 'AI Operations Platform',
    narrative: 'Deploy AI-powered operations management platform. Advanced demand forecasting, production scheduling, and quality prediction. Next-level efficiency.',
    cost: 0,
    impactMagnitude: 3,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    cogsImpact: -0.015,
    sgaImpact: -0.008,
    recurringBenefit: 75,
    optimizeMetrics: {
      implementationCost: 2.5,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 80,
    },

  },
  {
    id: 'optimize-5-2',
    decisionNumber: 68,
    category: 'optimize',
    subcategory: 'Global Supply Chain Redesign',
    name: 'Inventory Optimization',
    narrative: 'Implement advanced inventory management to reduce working capital requirements. Risk of stockouts during supply disruptions but significant cash release.',
    cost: 0,
    impactMagnitude: 2,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: '2. Cash is king',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    cogsImpact: -0.005,
    recurringBenefit: 40,
    optimizeMetrics: {
      implementationCost: 2,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 40,
    },

  },
  {
    id: 'optimize-5-3',
    decisionNumber: 69,
    category: 'optimize',
    subcategory: 'SG&A Optimization',
    name: 'Sales Force Effectiveness',
    narrative: 'Restructure the sales organization with targeted investment in CRM, analytics, and coverage model redesign, shifting from relationship-led to data-driven account management to improve customer coverage while reducing overall sales headcount.',
    cost: 0,
    impactMagnitude: 2,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: '2. Cash is king',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    sgaImpact: -0.01,
    recurringBenefit: 40,
    optimizeMetrics: {
      implementationCost: 3,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 40,
    },

  },
  {
    id: 'optimize-5-4',
    decisionNumber: 70,
    category: 'optimize',
    subcategory: 'Global Supply Chain Redesign',
    name: 'Near-Shoring Initiative',
    narrative: 'Shift supply chain closer to end markets. Higher unit costs offset by reduced logistics, inventory, and disruption risk. Resilience investment.',
    cost: 0,
    impactMagnitude: 3,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: '3. Stay flexible',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    cogsImpact: 0.005,
    riskPrevention: 'supply_chain_disruption',
    recurringBenefit: 50,
    optimizeMetrics: {
      implementationCost: 3,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 80,
    },

  },
  {
    id: 'optimize-5-5',
    decisionNumber: 71,
    category: 'optimize',
    subcategory: 'Factory of the Future',
    name: 'Full Smart Factory Rollout',
    narrative: 'Expand proven smart factory technologies across global manufacturing footprint. Recovery positions for investment. Strong ROI from scale.',
    cost: 360,
    impactMagnitude: 4,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    cogsImpact: -0.025,
    recurringBenefit: 130,
    optimizeMetrics: {
      implementationCost: 0,
      investment: 360,
      investmentPeriod: 1,
      annualCost: 120,
    },

  },
];

// =============================================================================
// SUSTAIN DECISIONS (Based on Excel - Lever = "Sustain")
// =============================================================================

const SUSTAIN_DECISIONS: Decision[] = [
  // ===== ROUND 1 =====
  {
    id: 'sustain-1-1',
    decisionNumber: 11,
    category: 'sustain',
    subcategory: 'Portfolio management (maintenance)',
    name: 'Customer Diversification Initiative',
    narrative: 'Allocate incremental investment to expand sales coverage and key-account capabilities beyond top customers, deliberately diversifying the revenue base and mitigating concentration risk.',
    cost: 40,
    impactMagnitude: 2,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    riskPrevention: 'key_customer_loss',
    recurringBenefit: 30,
    sustainMetrics: {
      implementationCost: 0,
      investment: 40,
      investmentPeriod: 1,
      annualCost: 0,
    },

  },
  {
    id: 'sustain-1-2',
    decisionNumber: 12,
    category: 'sustain',
    subcategory: 'Talent & Leadership Upskilling',
    name: 'Technical Talent Development',
    narrative: 'Investment in training and development for engineering workforce. Essential to maintain competitive capabilities. Retention and capability building.',
    cost: 0,
    impactMagnitude: 2,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    recurringBenefit: 20,
    sustainMetrics: {
      implementationCost: 3,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 40,
    },

  },
  {
    id: 'sustain-1-3',
    decisionNumber: 13,
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'Cybersecurity Enhancement',
    narrative: 'Comprehensive cybersecurity upgrade across IT infrastructure. Essential protection against growing cyber threats. No direct return but prevents catastrophic risk.',
    cost: 80,
    impactMagnitude: 2,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: '3. Stay flexible',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'cyber_attack',
    recurringBenefit: 0,
    sustainMetrics: {
      implementationCost: 0,
      investment: 80,
      investmentPeriod: 1,
      annualCost: 0,
    },

  },
  {
    id: 'sustain-1-4',
    decisionNumber: 14,
    category: 'sustain',
    subcategory: 'Capital allocation strategy (maintenance)',
    name: 'Equipment Refresh Program',
    narrative: 'Scheduled replacement of aging manufacturing equipment. Maintains reliability and quality. Deferred investment risks production disruptions.',
    cost: 80,
    impactMagnitude: 3,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'equipment_failure',
    recurringBenefit: 25,
    sustainMetrics: {
      implementationCost: 0,
      investment: 80,
      investmentPeriod: 1,
      annualCost: 0,
    },

  },
  {
    id: 'sustain-1-5',
    decisionNumber: 15,
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'Environmental Compliance Investment',
    narrative: 'Proactive investment to meet upcoming environmental regulations. Mandatory compliance but early investment avoids rushed future spending.',
    cost: 0,
    impactMagnitude: 2,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: '3. Stay flexible',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'regulatory_penalty',
    recurringBenefit: 15,
    sustainMetrics: {
      implementationCost: 3,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 40,
    },

  },

  // ===== ROUND 2 =====
  {
    id: 'sustain-2-1',
    decisionNumber: 26,
    category: 'sustain',
    subcategory: 'Talent & Leadership Upskilling',
    name: 'Leadership Development Program',
    narrative: 'Comprehensive leadership development for high-potential managers. Builds succession pipeline and organizational capability. Long-term investment in human capital.',
    cost: 0,
    impactMagnitude: 2,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    recurringBenefit: 25,
    sustainMetrics: {
      implementationCost: 3,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 40,
    },

  },
  {
    id: 'sustain-2-2',
    decisionNumber: 27,
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'Quality Management System Upgrade',
    narrative: 'Upgrade quality management systems to meet evolving OEM requirements. Essential for maintaining key customer relationships. Prevents costly quality escapes.',
    cost: 80,
    impactMagnitude: 2,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'quality_failure',
    recurringBenefit: 20,
    sustainMetrics: {
      implementationCost: 0,
      investment: 80,
      investmentPeriod: 1,
      annualCost: 0,
    },

  },
  {
    id: 'sustain-2-3',
    decisionNumber: 28,
    category: 'sustain',
    subcategory: 'Capital allocation strategy (maintenance)',
    name: 'IT Infrastructure Modernization',
    narrative: 'Update core IT systems and infrastructure. Addresses technical debt and security vulnerabilities. Foundational investment enabling future digital initiatives.',
    cost: 0,
    impactMagnitude: 2,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'system_failure',
    recurringBenefit: 30,
    sustainMetrics: {
      implementationCost: 3,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 40,
    },

  },
  {
    id: 'sustain-2-4',
    decisionNumber: 29,
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'Health & Safety Investment',
    narrative: 'Enhanced workplace safety equipment and training programs. Essential for employee welfare and regulatory compliance. Reduces accident-related costs.',
    cost: 40,
    impactMagnitude: 1,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: '3. Stay flexible',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'safety_incident',
    recurringBenefit: 15,
    sustainMetrics: {
      implementationCost: 0,
      investment: 40,
      investmentPeriod: 1,
      annualCost: 0,
    },

  },
  {
    id: 'sustain-2-5',
    decisionNumber: 30,
    category: 'sustain',
    subcategory: 'Portfolio management (maintenance)',
    name: 'Supplier Relationship Investment',
    narrative: 'Strengthen relationships with strategic suppliers through joint development and long-term agreements. Improves supply security and preferential allocation.',
    cost: 0,
    impactMagnitude: 2,
    introducedYear: 2,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'supply_chain_disruption',
    recurringBenefit: 20,
    sustainMetrics: {
      implementationCost: 3,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 40,
    },

  },

  // ===== ROUND 3 =====
  {
    id: 'sustain-3-1',
    decisionNumber: 41,
    category: 'sustain',
    subcategory: 'Portfolio management (maintenance)',
    name: 'Contract Renewal Defense',
    narrative: 'Invest in proactive retention programs—including dedicated renewal teams, pricing/offer analytics, and targeted customer incentives—to secure contract renewals in a more competitive environment and protect at-risk revenue.',
    cost: 80,
    impactMagnitude: 2,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'key_customer_loss',
    recurringBenefit: 35,
    sustainMetrics: {
      implementationCost: 0,
      investment: 80,
      investmentPeriod: 1,
      annualCost: 0,
    },

  },
  {
    id: 'sustain-3-2',
    decisionNumber: 42,
    category: 'sustain',
    subcategory: 'Capital allocation strategy (maintenance)',
    name: 'Critical Equipment Maintenance',
    narrative: 'Essential maintenance program for production-critical equipment. Tempting to defer during cost pressure but failure would be catastrophic.',
    cost: 0,
    impactMagnitude: 3,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: '3. Stay flexible',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'equipment_failure',
    recurringBenefit: 30,
    sustainMetrics: {
      implementationCost: 3,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 80,
    },

  },
  {
    id: 'sustain-3-3',
    decisionNumber: 43,
    category: 'sustain',
    subcategory: 'Talent & Leadership Upskilling',
    name: 'Key Talent Retention Program',
    narrative: 'Targeted retention incentives for critical technical and leadership talent. Important to maintain during cost pressures when competitors may poach.',
    cost: 120,
    impactMagnitude: 3,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'talent_loss',
    recurringBenefit: 25,
    sustainMetrics: {
      implementationCost: 0,
      investment: 120,
      investmentPeriod: 1,
      annualCost: 0,
    },

  },
  {
    id: 'sustain-3-4',
    decisionNumber: 44,
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'Business Continuity Enhancement',
    narrative: 'Strengthen business continuity planning and backup capabilities. Particularly important as risks increase during economic uncertainty.',
    cost: 80,
    impactMagnitude: 2,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: '3. Stay flexible',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'business_disruption',
    recurringBenefit: 15,
    sustainMetrics: {
      implementationCost: 0,
      investment: 80,
      investmentPeriod: 1,
      annualCost: 0,
    },

  },
  {
    id: 'sustain-3-5',
    decisionNumber: 45,
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'Insurance Coverage Upgrade',
    narrative: 'Enhance insurance coverage for key operational and financial risks. Higher premiums but better protection against tail risks during uncertain times.',
    cost: 40,
    impactMagnitude: 1,
    introducedYear: 3,
    type: 'organic',
    guidingPrinciple: '3. Stay flexible',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'catastrophic_loss',
    recurringBenefit: 10,
    sustainMetrics: {
      implementationCost: 0,
      investment: 40,
      investmentPeriod: 1,
      annualCost: 0,
    },

  },

  // ===== ROUND 4 =====
  {
    id: 'sustain-4-1',
    decisionNumber: 56,
    category: 'sustain',
    subcategory: 'Organizational Restructure',
    name: 'Deep Cost Restructuring',
    narrative: 'Aggressive cost reduction program across all functions. Difficult decisions but necessary for survival in prolonged downturn. Risk of capability damage.',
    cost: 0,
    impactMagnitude: 5,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: '2. Cash is king',
    isRisky: true,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    sgaImpact: -0.04,
    cogsImpact: -0.02,
    recurringBenefit: 150,
    sustainMetrics: {
      implementationCost: 3,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 160,
    },

  },
  {
    id: 'sustain-4-2',
    decisionNumber: 57,
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'Regulatory Compliance Baseline',
    narrative: 'Fund mandatory regulatory compliance at the minimum required level, deliberately limiting scope to avoid incremental spend while maintaining license to operate.',
    cost: 0,
    impactMagnitude: 2,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: '3. Stay flexible',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'regulatory_penalty',
    recurringBenefit: 10,
    sustainMetrics: {
      implementationCost: 3,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 40,
    },

  },
  {
    id: 'sustain-4-3',
    decisionNumber: 58,
    category: 'sustain',
    subcategory: 'Capital allocation strategy (maintenance)',
    name: 'Minimum Viable Maintenance',
    narrative: 'Bare minimum maintenance investment to keep operations running. Risk of equipment failure but preserves cash during severe downturn.',
    cost: 80,
    impactMagnitude: 2,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: true,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'equipment_failure',
    recurringBenefit: 15,
    sustainMetrics: {
      implementationCost: 0,
      investment: 80,
      investmentPeriod: 1,
      annualCost: 0,
    },

  },
  {
    id: 'sustain-4-4',
    decisionNumber: 59,
    category: 'sustain',
    subcategory: 'Talent & Leadership Upskilling',
    name: 'Core Team Preservation',
    narrative: 'Investment to retain absolutely critical talent through recession. Skeletal but essential team for recovery. Others may be rehired post-downturn.',
    cost: 120,
    impactMagnitude: 3,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'talent_loss',
    recurringBenefit: 20,
    sustainMetrics: {
      implementationCost: 0,
      investment: 120,
      investmentPeriod: 1,
      annualCost: 0,
    },

  },
  {
    id: 'sustain-4-5',
    decisionNumber: 60,
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'Financial Risk Management',
    narrative: 'Enhanced treasury and financial risk management during volatile conditions. Hedge exposures and manage liquidity carefully.',
    cost: 0,
    impactMagnitude: 2,
    introducedYear: 4,
    type: 'organic',
    guidingPrinciple: '3. Stay flexible',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'financial_risk',
    recurringBenefit: 15,
    sustainMetrics: {
      implementationCost: 3,
      investment: 0,
      investmentPeriod: 1,
      annualCost: 40,
    },

  },

  // ===== ROUND 5 =====
  {
    id: 'sustain-5-1',
    decisionNumber: 72,
    category: 'sustain',
    subcategory: 'Capital allocation strategy (maintenance)',
    name: 'Deferred Maintenance Catch-Up',
    narrative: 'Address deferred maintenance from recession period. Essential to restore equipment reliability for recovery. May require higher spend than normal.',
    cost: 120,
    impactMagnitude: 3,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'equipment_failure',
    recurringBenefit: 40,
    sustainMetrics: {
      implementationCost: 0,
      investment: 120,
      investmentPeriod: 1,
      annualCost: 0,
    },

  },
  {
    id: 'sustain-5-2',
    decisionNumber: 73,
    category: 'sustain',
    subcategory: 'Talent & Leadership Upskilling',
    name: 'Workforce Rebuilding Program',
    narrative: 'Rehire and retrain workforce for recovery volumes. Compete for talent returning to job market. Investment in recruiting and onboarding.',
    cost: 120,
    impactMagnitude: 3,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    recurringBenefit: 35,
    sustainMetrics: {
      implementationCost: 0,
      investment: 120,
      investmentPeriod: 1,
      annualCost: 0,
    },

  },
  {
    id: 'sustain-5-3',
    decisionNumber: 74,
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'ESG & Sustainability Investment',
    narrative: 'Comprehensive ESG program to meet growing stakeholder expectations. Carbon reduction, sustainable materials, and governance enhancement.',
    cost: 40,
    impactMagnitude: 2,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    riskPrevention: 'esg_risk',
    recurringBenefit: 30,
    sustainMetrics: {
      implementationCost: 0,
      investment: 40,
      investmentPeriod: 1,
      annualCost: 0,
    },

  },
  {
    id: 'sustain-5-4',
    decisionNumber: 75,
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'Post-Crisis Risk Assessment',
    narrative: 'Comprehensive review and update of risk management framework based on lessons learned. Prepare for next downturn while positioned for recovery.',
    cost: 40,
    impactMagnitude: 1,
    introducedYear: 5,
    type: 'organic',
    guidingPrinciple: '1. Grow profitably',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    riskPrevention: 'business_disruption',
    recurringBenefit: 20,
    sustainMetrics: {
      implementationCost: 0,
      investment: 40,
      investmentPeriod: 1,
      annualCost: 0,
    },

  },
];

// =============================================================================
// EXPORTS
// =============================================================================

/** All decision cards (76 total based on Excel: 26 Grow + 25 Optimize + 25 Sustain) */
export const ALL_DECISIONS: Decision[] = [
  ...GROW_DECISIONS,
  ...OPTIMIZE_DECISIONS,
  ...SUSTAIN_DECISIONS,
];

/**
 * Get decisions available for a specific round
 * Returns decisions introduced in that round
 */
export function getDecisionsForRound(round: RoundNumber): Decision[] {
  return ALL_DECISIONS.filter(d => d.introducedYear === round);
}

/**
 * Get decisions by category
 */
export function getDecisionsByCategory(category: 'grow' | 'optimize' | 'sustain'): Decision[] {
  return ALL_DECISIONS.filter(d => d.category === category);
}

/**
 * Get a single decision by ID
 */
export function getDecisionById(id: string): Decision | undefined {
  return ALL_DECISIONS.find(d => d.id === id);
}

/**
 * Get all risky decisions
 */
export function getRiskyDecisions(): Decision[] {
  return ALL_DECISIONS.filter(d => d.isRisky);
}

/**
 * Validate decision configuration
 * Note: Excel data has 26 Grow, 25 Optimize, 24 Sustain (76 total for Grow/Optimize, 24 for Sustain in Round 5)
 */
export function validateDecisionConfiguration(): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  
  // Check for at least 75 decisions
  if (ALL_DECISIONS.length < 75) {
    errors.push(`Expected at least 75 decisions, found ${ALL_DECISIONS.length}`);
  }
  
  // Check that each round has decisions
  for (let round = 1; round <= 5; round++) {
    const roundDecisions = getDecisionsForRound(round as RoundNumber);
    if (roundDecisions.length < 12) {
      errors.push(`Round ${round} has only ${roundDecisions.length} decisions, expected at least 12`);
    }
  }
  
  // Check for duplicate IDs
  const ids = ALL_DECISIONS.map(d => d.id);
  const uniqueIds = new Set(ids);
  if (uniqueIds.size !== ids.length) {
    const duplicates = ids.filter((id, index) => ids.indexOf(id) !== index);
    errors.push(`Duplicate decision IDs found: ${duplicates.join(', ')}`);
  }
  
  return {
    valid: errors.length === 0,
    errors,
  };
}
