/**
 * Demo Mode Data
 * 
 * Mock data for frontend-only demo mode.
 * Allows testing the UI/UX without a backend server.
 */

import type { GameState, Decision, RoundResults, FinalResults, TeamRoundSnapshot, RoundNumber } from '@/types/game';

// =============================================================================
// Demo Decisions (Sample from each category)
// =============================================================================

export const DEMO_DECISIONS: Decision[] = [
  // GROW decisions
  {
    id: 'demo-grow-1',
    decisionNumber: 1,
    category: 'grow',
    subcategory: 'JV / Strategic Partnership',
    name: 'Battery Technology JV',
    narrative: 'Form a joint venture with a leading battery manufacturer to secure supply chain positioning and access next-gen battery technology.',
    cost: 400,
    impactMagnitude: 4,
    introducedYear: 1,
    type: 'inorganic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: false,
    durationYears: 2,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.035,
    recurringBenefit: 140,
  },
  {
    id: 'demo-grow-2',
    decisionNumber: 2,
    category: 'grow',
    subcategory: 'Acquire a Business',
    name: 'Autonomous Driving Software Acquisition',
    narrative: 'Acquire a promising autonomous driving software startup to accelerate ADAS capabilities.',
    cost: 550,
    impactMagnitude: 5,
    introducedYear: 1,
    type: 'inorganic',
    guidingPrinciple: 'Position for recovery',
    isRisky: true,
    durationYears: 2,
    rampUpYears: 3,
    isOneTimeBenefit: false,
    revenueImpact: 0.04,
    recurringBenefit: 180,
  },
  {
    id: 'demo-grow-3',
    decisionNumber: 3,
    category: 'grow',
    subcategory: 'Expand Manufacturing Footprint',
    name: 'Mexico Manufacturing Expansion',
    narrative: 'Build new manufacturing facility in Mexico to serve North American OEMs with lower logistics costs.',
    cost: 350,
    impactMagnitude: 3,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Position for recovery',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    revenueImpact: 0.02,
    recurringBenefit: 80,
  },
  // OPTIMIZE decisions
  {
    id: 'demo-optimize-1',
    decisionNumber: 6,
    category: 'optimize',
    subcategory: 'Factory of the Future',
    name: 'AI-Powered Quality Control',
    narrative: 'Deploy machine learning systems across manufacturing lines to reduce defect rates and warranty costs.',
    cost: 150,
    impactMagnitude: 3,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    cogsImpact: -0.01,
    recurringBenefit: 60,
  },
  {
    id: 'demo-optimize-2',
    decisionNumber: 7,
    category: 'optimize',
    subcategory: 'Global Supply Chain Redesign',
    name: 'Supply Chain Digitization',
    narrative: 'Implement end-to-end supply chain visibility platform to reduce inventory costs and improve supplier management.',
    cost: 120,
    impactMagnitude: 2,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    cogsImpact: -0.005,
    sgaImpact: -0.01,
    recurringBenefit: 50,
  },
  {
    id: 'demo-optimize-3',
    decisionNumber: 8,
    category: 'optimize',
    subcategory: 'Select Group Transformation',
    name: 'Lean Manufacturing Initiative',
    narrative: 'Deploy lean manufacturing principles across legacy plants to improve throughput and reduce waste.',
    cost: 80,
    impactMagnitude: 2,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Margin expansion > Growth',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    cogsImpact: -0.008,
    recurringBenefit: 40,
  },
  // SUSTAIN decisions
  {
    id: 'demo-sustain-1',
    decisionNumber: 11,
    category: 'sustain',
    subcategory: 'Risk & Compliance Upgrade',
    name: 'Carbon Neutral Manufacturing',
    narrative: 'Invest in renewable energy and carbon offset programs to achieve carbon neutrality at key facilities.',
    cost: 200,
    impactMagnitude: 2,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    recurringBenefit: 30,
    riskPrevention: 'esg_risk',
  },
  {
    id: 'demo-sustain-2',
    decisionNumber: 12,
    category: 'sustain',
    subcategory: 'Talent & Leadership Upskilling',
    name: 'Workforce Upskilling Program',
    narrative: 'Comprehensive training program to prepare workforce for advanced and software-defined vehicle manufacturing.',
    cost: 100,
    impactMagnitude: 2,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Position for recovery',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 2,
    isOneTimeBenefit: false,
    recurringBenefit: 25,
    riskPrevention: 'talent_loss',
  },
  {
    id: 'demo-sustain-3',
    decisionNumber: 13,
    category: 'sustain',
    subcategory: 'Portfolio management (maintenance)',
    name: 'Supplier Diversity Initiative',
    narrative: 'Develop relationships with diverse suppliers to improve supply chain resilience and meet OEM requirements.',
    cost: 60,
    impactMagnitude: 2,
    introducedYear: 1,
    type: 'organic',
    guidingPrinciple: 'Diversification pays off',
    isRisky: false,
    durationYears: 1,
    rampUpYears: 1,
    isOneTimeBenefit: false,
    recurringBenefit: 20,
    riskPrevention: 'supply_chain_disruption',
  },
];

// =============================================================================
// Demo Game State
// =============================================================================

export function createDemoGameState(
  round: RoundNumber = 1, 
  status: 'lobby' | 'active' | 'results' | 'finished' = 'lobby',
  userTeamName?: string
): GameState {
  return {
    status,
    currentRound: round,
    roundTimeRemaining: 180,
    roundDuration: 180,
    teamCount: 5,
    teams: {
      1: {
        teamId: 1,
        teamName: userTeamName || 'Your Team',
        isClaimed: true,
        socketId: 'demo-socket-1',
        cashBalance: 1000,
        currentRoundDecisions: [],
        allDecisions: [],
        metrics: {
          revenue: 42836,
          ebitda: 3200,
          ebit: 2116,
          ebitMargin: 0.0494,
          operatingFCF: 1561,
          capex: -1200,
          roic: 0.085,
        },
        stockPrice: 52.50,
        cumulativeTSR: 0.065,
        roundTSR: 0.032,
        hasSubmitted: false,
        draftDecisionIds: [],
      },
      2: {
        teamId: 2,
        teamName: 'Beta Capital',
        isClaimed: true,
        socketId: 'demo-socket-2',
        cashBalance: 850,
        currentRoundDecisions: [],
        allDecisions: [],
        metrics: {
          revenue: 43500,
          ebitda: 3100,
          ebit: 2050,
          ebitMargin: 0.0471,
          operatingFCF: 1480,
          capex: -1150,
          roic: 0.082,
        },
        stockPrice: 51.20,
        cumulativeTSR: 0.039,
        roundTSR: 0.018,
        hasSubmitted: false,
        draftDecisionIds: [],
      },
      3: {
        teamId: 3,
        teamName: 'Gamma Growth',
        isClaimed: true,
        socketId: 'demo-socket-3',
        cashBalance: 920,
        currentRoundDecisions: [],
        allDecisions: [],
        metrics: {
          revenue: 44200,
          ebitda: 3350,
          ebit: 2200,
          ebitMargin: 0.0498,
          operatingFCF: 1620,
          capex: -1280,
          roic: 0.088,
        },
        stockPrice: 54.80,
        cumulativeTSR: 0.112,
        roundTSR: 0.055,
        hasSubmitted: false,
        draftDecisionIds: [],
      },
      4: {
        teamId: 4,
        teamName: 'Delta Partners',
        isClaimed: false,
        cashBalance: 1000,
        currentRoundDecisions: [],
        allDecisions: [],
        metrics: {
          revenue: 42836,
          ebitda: 3200,
          ebit: 2116,
          ebitMargin: 0.0494,
          operatingFCF: 1561,
          capex: -1200,
          roic: 0.085,
        },
        stockPrice: 49.29,
        cumulativeTSR: 0,
        roundTSR: 0,
        hasSubmitted: false,
        draftDecisionIds: [],
      },
      5: {
        teamId: 5,
        teamName: 'Epsilon Equity',
        isClaimed: false,
        cashBalance: 1000,
        currentRoundDecisions: [],
        allDecisions: [],
        metrics: {
          revenue: 42836,
          ebitda: 3200,
          ebit: 2116,
          ebitMargin: 0.0494,
          operatingFCF: 1561,
          capex: -1200,
          roic: 0.085,
        },
        stockPrice: 49.29,
        cumulativeTSR: 0,
        roundTSR: 0,
        hasSubmitted: false,
        draftDecisionIds: [],
      },
    },
    scenario: {
      round: round,
      name: 'Business as Usual',
      description: 'Standard market conditions with moderate growth expectations.',
      marketGrowth: 0.02,
      revenueMultiplier: 1.0,
      costMultiplier: 1.0,
    },
    riskyEvents: {
      hasActiveRiskyEvent: false,
    },
    startedAt: new Date().toISOString(),
    roundStartedAt: new Date().toISOString(),
  };
}

// =============================================================================
// Demo Round Results
// =============================================================================

export function createDemoRoundResults(round: RoundNumber): RoundResults {
  return {
    round,
    teamResults: [
      {
        teamId: 3,
        rank: 1,
        stockPrice: 54.80,
        stockPriceChange: 2.50,
        roundTSR: 0.055,
        cumulativeTSR: 0.112,
        decisionsCount: 3,
      },
      {
        teamId: 1,
        rank: 2,
        stockPrice: 52.50,
        stockPriceChange: 1.80,
        roundTSR: 0.032,
        cumulativeTSR: 0.065,
        decisionsCount: 2,
      },
      {
        teamId: 2,
        rank: 3,
        stockPrice: 51.20,
        stockPriceChange: 0.90,
        roundTSR: 0.018,
        cumulativeTSR: 0.039,
        decisionsCount: 4,
      },
    ],
    scenarioNarrative: 'The automotive sector saw steady growth this quarter as technology investments continued to pay off.',
    marketOutlook: {
      backwardStatements: [
        'Technology adoption exceeded expectations, driving component demand higher.',
        'Supply chain pressures eased as semiconductor availability improved.',
      ],
      forwardStatements: [
        'Cost pressures expected to intensify as raw material prices rise.',
        'OEM consolidation may create new partnership opportunities.',
      ],
    },
  };
}

// =============================================================================
// Demo Final Results
// =============================================================================

export function createDemoFinalResults(): FinalResults {
  const teamHistories: Record<number, TeamRoundSnapshot[]> = {
    1: [
      { round: 1 as RoundNumber, stockPrice: 50.50, tsr: 0.025, cashBalance: 850, decisionsSubmitted: ['demo-grow-1', 'demo-optimize-1'], metrics: { stockPrice: 50.50, roic: 0.086, revenueGrowth: 0.02, ebitdaMargin: 0.075, ebitMargin: 0.050, cogsToRevenue: 0.82, sgaToRevenue: 0.08 } },
      { round: 2 as RoundNumber, stockPrice: 51.80, tsr: 0.026, cashBalance: 720, decisionsSubmitted: ['demo-grow-2'], metrics: { stockPrice: 51.80, roic: 0.088, revenueGrowth: 0.025, ebitdaMargin: 0.076, ebitMargin: 0.051, cogsToRevenue: 0.81, sgaToRevenue: 0.08 } },
      { round: 3 as RoundNumber, stockPrice: 50.20, tsr: -0.031, cashBalance: 680, decisionsSubmitted: [], metrics: { stockPrice: 50.20, roic: 0.082, revenueGrowth: -0.01, ebitdaMargin: 0.072, ebitMargin: 0.047, cogsToRevenue: 0.83, sgaToRevenue: 0.085 } },
      { round: 4 as RoundNumber, stockPrice: 48.50, tsr: -0.034, cashBalance: 620, decisionsSubmitted: ['demo-optimize-2'], metrics: { stockPrice: 48.50, roic: 0.078, revenueGrowth: -0.05, ebitdaMargin: 0.068, ebitMargin: 0.042, cogsToRevenue: 0.84, sgaToRevenue: 0.09 } },
      { round: 5 as RoundNumber, stockPrice: 52.50, tsr: 0.082, cashBalance: 580, decisionsSubmitted: ['demo-grow-3', 'demo-sustain-1'], metrics: { stockPrice: 52.50, roic: 0.085, revenueGrowth: 0.06, ebitdaMargin: 0.075, ebitMargin: 0.049, cogsToRevenue: 0.82, sgaToRevenue: 0.08 } },
    ],
    2: [
      { round: 1 as RoundNumber, stockPrice: 50.00, tsr: 0.014, cashBalance: 900, decisionsSubmitted: ['demo-optimize-1'], metrics: { stockPrice: 50.00, roic: 0.084, revenueGrowth: 0.015, ebitdaMargin: 0.074, ebitMargin: 0.049, cogsToRevenue: 0.82, sgaToRevenue: 0.08 } },
      { round: 2 as RoundNumber, stockPrice: 50.50, tsr: 0.010, cashBalance: 850, decisionsSubmitted: ['demo-sustain-2'], metrics: { stockPrice: 50.50, roic: 0.085, revenueGrowth: 0.018, ebitdaMargin: 0.074, ebitMargin: 0.049, cogsToRevenue: 0.82, sgaToRevenue: 0.08 } },
      { round: 3 as RoundNumber, stockPrice: 49.80, tsr: -0.014, cashBalance: 800, decisionsSubmitted: [], metrics: { stockPrice: 49.80, roic: 0.082, revenueGrowth: -0.008, ebitdaMargin: 0.072, ebitMargin: 0.047, cogsToRevenue: 0.83, sgaToRevenue: 0.085 } },
      { round: 4 as RoundNumber, stockPrice: 47.20, tsr: -0.052, cashBalance: 750, decisionsSubmitted: ['demo-grow-1'], metrics: { stockPrice: 47.20, roic: 0.076, revenueGrowth: -0.06, ebitdaMargin: 0.066, ebitMargin: 0.040, cogsToRevenue: 0.85, sgaToRevenue: 0.09 } },
      { round: 5 as RoundNumber, stockPrice: 51.20, tsr: 0.085, cashBalance: 700, decisionsSubmitted: ['demo-grow-2'], metrics: { stockPrice: 51.20, roic: 0.082, revenueGrowth: 0.05, ebitdaMargin: 0.073, ebitMargin: 0.047, cogsToRevenue: 0.82, sgaToRevenue: 0.085 } },
    ],
    3: [
      { round: 1 as RoundNumber, stockPrice: 51.50, tsr: 0.045, cashBalance: 800, decisionsSubmitted: ['demo-grow-1', 'demo-grow-2'], metrics: { stockPrice: 51.50, roic: 0.090, revenueGrowth: 0.035, ebitdaMargin: 0.078, ebitMargin: 0.052, cogsToRevenue: 0.80, sgaToRevenue: 0.078 } },
      { round: 2 as RoundNumber, stockPrice: 53.20, tsr: 0.033, cashBalance: 680, decisionsSubmitted: ['demo-optimize-1'], metrics: { stockPrice: 53.20, roic: 0.092, revenueGrowth: 0.04, ebitdaMargin: 0.080, ebitMargin: 0.054, cogsToRevenue: 0.79, sgaToRevenue: 0.076 } },
      { round: 3 as RoundNumber, stockPrice: 52.00, tsr: -0.023, cashBalance: 650, decisionsSubmitted: [], metrics: { stockPrice: 52.00, roic: 0.088, revenueGrowth: 0.00, ebitdaMargin: 0.076, ebitMargin: 0.050, cogsToRevenue: 0.81, sgaToRevenue: 0.08 } },
      { round: 4 as RoundNumber, stockPrice: 50.50, tsr: -0.029, cashBalance: 600, decisionsSubmitted: ['demo-grow-3'], metrics: { stockPrice: 50.50, roic: 0.084, revenueGrowth: -0.03, ebitdaMargin: 0.072, ebitMargin: 0.046, cogsToRevenue: 0.82, sgaToRevenue: 0.085 } },
      { round: 5 as RoundNumber, stockPrice: 54.80, tsr: 0.085, cashBalance: 550, decisionsSubmitted: ['demo-grow-1', 'demo-sustain-1'], metrics: { stockPrice: 54.80, roic: 0.088, revenueGrowth: 0.07, ebitdaMargin: 0.078, ebitMargin: 0.050, cogsToRevenue: 0.80, sgaToRevenue: 0.078 } },
    ],
  };

  return {
    winnerId: 3,
    leaderboard: [
      {
        teamId: 3,
        rank: 1,
        finalStockPrice: 54.80,
        startingStockPrice: 49.29,
        totalTSR: 0.112,
        totalDividends: 2.50,
      },
      {
        teamId: 1,
        rank: 2,
        finalStockPrice: 52.50,
        startingStockPrice: 49.29,
        totalTSR: 0.065,
        totalDividends: 2.20,
      },
      {
        teamId: 2,
        rank: 3,
        finalStockPrice: 51.20,
        startingStockPrice: 49.29,
        totalTSR: 0.039,
        totalDividends: 2.00,
      },
    ],
    teamHistories,
  };
}
